<?php
$l_readm_title		 = "Lire les messages";
$l_readm_delete		 = "MESSAGE EFFACÉ";
$l_readm_nomessage	 = "Vous n'avez aucun message en attente";
$l_readm_center		 = "Centre de messagerie";
$l_readm_sender		 = "Source";
$l_readm_captn		 = "Capitaine du ";
$l_readm_del		 = "Effacer";
$l_readm_repl		 = "Répondre";
$l_readm_return            = "Click here to return to the main menu";
$l_readm_title2            = "Mail Reader";
$l_readm_delete            = "Delete All";
$l_readm_subject            = "Subject";
$l_readm_quote            = "Quote";
$l_readm_block            = "Block Sender";
$l_readm_alert            = "System Alert";
$l_readm_alertbody            = "Ship Computer";
?>
