<?php
$l_pre_title = "Changer les raccourcis d'espace réel";
$l_pre_exceed = "Le raccourci [preset] dépasse le nombre maximum de secteurs [sector_max]. Aucun raccourci sauvegardé.<BR><BR>";
$l_pre_set = "Le raccourci";
$l_pre_save = "Sauvegarder";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
