<?php
// New News Items

$l_news_planets		 = " planetes";
$l_news_cols		 = " Million de colons";
$l_news_p_headline 	 = "Empire [player] a à present [total] planetes";
$l_news_c_headline 	 = "Empire [player] a à present [total] million de colons";
$l_news_p_textXX	 = "The Federation has issued warnings concerning the Empire of [name].  [name] has control of [total] planets and should be considered very dangerous.  All sectors should increase sector defenses immediately.";
$l_news_c_textXX	 = "The Empire of [name] is experiencing massive overcrowding on all planets with over [total] million colonists.  Food shortages may cause unrest.  All sectors should be aware of possible aggressive actions by [name] in the future.";

$l_created_universe             = 'Création D\'Univers';
$l_created_universe_full        = 'Les scientifiques recherchant le commencements de l\'univers ont unanimement décidé que c\'est aujourd\'hui le jour le plus statistiquement  probable pour que la création d\'univers ait lieu';

$l_news_p_text5		 = "L'empire emergeant de [name] a maintenant cinq planètes, le FNN observera les actions de [name] plus étroitement à l'avenir!";
$l_news_p_text10	 = "L'empire croissant de [name] controle maintenant dix planètes, Les rapports de FNN indiquent cette autre expansion de [name] pourrait engendrer la guerre!";
$l_news_p_text25	 = "L'énorme Empire de [name] qui a déjà colonisé 25 planètes, dans une entrevue, [name] a annoncé qu'il pourrait ralentir son expansion à l'avenir!";
$l_news_p_text50	 = "L'énorme et vaste empire de [name], représenté par 50 planètes dans la galaxie entière represente une force menaçante. Un des journalistes de FNN a découvert que [name] améliore son vaisseau, projetant une guerre importante. Dans une entrevue, [name] a annoncé que c'est seulement dans un but défenssif!";
$l_news_c_text25	 = "L'empire emmergeant de [name] a maintenant 25 millions de colons, le FNN observera les actions de [name] plus étroitement à l'avenir, mais il est fortement évident que le taux de naissance vas éclater!";
$l_news_c_text100	 = "L'empire de [name] a maintenant 100 millions de colons, après une explosion du taux de natalité, les colonies de [name] semble être un bon endroit pour les familles.!";
$l_news_c_text500	 = "Le grand empire de [name] a maintenant 500 millions colons, [name] dit dans une entrevue que la colonisation de la galaxie à juste seulement commencé";
$l_news_c_text1000	 = "L'empire giguentesque de [name] a maintenant un milliard de colons, Les journalistes de FNN ont découvert que [name] est en possesion d'un certain mécanisme étrange de clonage, lui permettant de multiplier de nouveaux colons dans des montants énormes. Avec cette quantité de colons, la force economique de cet empire est énorme, FNN espère que [name] ne dépense pas son argent pour une future guerre";

$l_news_indi_short	 = "Rumeur de FNN: au-dessus de [planets] déclarez l'independance.";
$l_news_indi	 = "FNN a de sources sures que plus de [planets] planètes ont décidé qu'elles serai mieux gerer par elles-mêmes et sont devenues independant.";

$l_news_nova_short	 = "Rapport de FNN: [name] a utilisé la bombe Nova.";
$l_news_nova	 = "FNN divulgue la nouvelles que [name] a employé la terrible bombe nova [total] fois pour détruire une planète et tous les vaisseaux qui s'y trouvaient.";
$l_news_nova_m_short	 = "Rapport de FNN: [name] a utilisé la bombe Nova et manqua sa cible.";
$l_news_nova_m	 = "FNN divulgue la nouvelles que [name] a employé la terrible bombe nova [total] fois pour essayer de détruire une planète.  La bombe nova a explosé en dehors de l'atmosphère de le planète et a endommagé massivement l'infrastructure planétaire.";

$l_news_bounty	 = "Rapport de FNN: [name] place une prime de [amount] sur la tete de [name2].";

$l_news_attackerpod_p_short	 = "Rapport de FNN: le vaisseau de [name] a ete detruit.";
$l_news_attackerpod_P	 = "le vaisseau de [name] a été détruit en attaquant une planète.  Heureusement, [name] avait un module d'evaquation et a survécu.";

$l_news_attackerdie_p_short	 = "Rapport de FNN: [name] est mort!";
$l_news_attackerdie_p	 = "le vaisseau de [name] a été détruit en attaquant une planète et il a été tués parce qu'il n'avait pas acheté une module d'évaquation.";

$l_news_destroyed_p_short	 = "Rapport de FNN: [name] attaque et détruit une planète!";
$l_news_destroyed_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] mais la population a prefer détruire la planète plutot que d'etre capturé!";

$l_news_defeated_p_short	 = "Rapport de FNN: [name] attaque et detruits les defenses d'une planete!";
$l_news_defeated_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] et défait les forces planétaires de défense!";

$l_news_notdefeated_p_short	 = "Rapport de FNN: [name] attaque une planète et perd!";
$l_news_notdefeated_p	 = "[name] a attaqué [total] fois la planete possédé par [owner] et les défenses planétaires ont tenues contre les attaques implacables!";

$l_news_targetepod_short	 = "Rapport de FNN: [name] attaque [owner] et gagne!";
$l_news_targetepod	 = "[name] a attaqué le vaisseau de [owner] et le detruit completement. Heureusement, [owner] avait equipé son vaisseau avec un module d'évaquation et il a survécu.";

$l_news_targetdies_short	 = "Rapport de FNN: [name] attaque [owner] et le tue!";
$l_news_targetdies	 = "[name] a attaqué le vaisseau de [owner] et le detruit completement.  Malheureusement [owner] n'avait pas equipé son vaisseau avec un module d'évaquation et il a été vaporisés.";

$l_news_fedcolbounty_short	 = "FNN Report: The Federation cracks down on [name]!";
$l_news_fedcolbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which inflicted [amount] credits worth of damage on the pirate's vessel.  Federation officials promise further such actions in the future!";

$l_news_alliancecolbounty_short	 = "FNN Report: The Alliance cracks down on [name]!";
$l_news_alliancecolbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which inflicted [amount] credits worth of damage on the pirate's vessel.  Alliance officials promise further such actions in the future!";

$l_news_fedcol_pbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_pbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_pbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_pbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Alliance officials promise further such actions in the future!";

$l_news_fedcol_sbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_sbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated a ship ([shiptype]) worth [cost] in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_sbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_sbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated a ship [shiptype] worth [cost] in sector [sector].  Alliance officials promise further such actions in the future!";

$l_killheadline		 ="[target] a été tué dans un accident";
$l_news_killed 		 = "[target] a été tué dans un accident tragique aujourd'hui. héroïquement - le captaine [target] était le dernier membre à bord de son vaisseau, quand il a noté qu'il n'y avait plus de module d'evacuation pour lui. Qu'il reposent en paix !";

$l_killSDheadline		 ="[target] was killed by Sector Defenses.";
$l_news_killedSD 		 = "[target] was killed by an overwhelming number of Sector Defenses owned by [killer]! Sadly, the ship was not equipped with an escape pod.";

$l_killplanetheadline		 ="[target] was killed attacking a planet.";
$l_news_killedplanet 		 = "[target] was killed while attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killshipheadline		 ="[target] was killed ship combat.";
$l_news_killedship 		 = "[target] was killed in ship to ship combat with [killer] today. The captain apparently forgot to equip the ship with an escape pod.";

$l_killsuicideheadline		 ="[target] commited suicide.";
$l_news_killedsuicide 		 = "[target] committed suicide today.  They took the cowards way out because they lacked the ability or courage to stand up to the pressures of commanding their own ship.";

$l_killsofaheadline		 ="[target] was killed sofa attacking a planet.";
$l_news_killedsofa 		 = "[target] was killed while sofa attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovaheadline		 ="[target] was killed during a nova attack.";
$l_news_killednova 		 = "[target] was killed by [killer] during a nova bomb attack today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovabackfireheadline		 ="[target] was killed from a nova backfire.";
$l_news_killednovabackfire 		 = "[target] was killed when their nova bomb backfired today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killsectormissileheadline		 ="[target] was killed from a Sector Missile.";
$l_news_killedsectormissile 		 = "[target] was killed when a Sector Missile from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killhunterprobeheadline		 ="[target] was killed from a Hunter Probe.";
$l_news_killedhunterprobe 		 = "[target] was killed when a Hunter Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killtrapprobeheadline		 ="[target] was killed from a Sentry Trap Probe.";
$l_news_killedtrapprobe 		 = "[target] was killed when a Sentry Trap Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

//-------------------

$l_killpodheadline		 ="[target]'s ship was destroyed in an accident";
$l_news_killedpod 		 = "[target]'s ship was destroyed in a tragic accident today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killSDpodheadline		 ="[target]'s ship was destroyed by Sector Defenses.";
$l_news_killedSDpod  		 = "[target]'s ship was destroyed by an overwhelming number of Sector Defenses owned by [killer]! An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killplanetpodheadline		 ="[target]'s ship was destroyed attacking a planet.";
$l_news_killedplanetpod  		 = "[target]'s ship was destroyed while attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killshippodheadline		 ="[target]'s ship was destroyed in ship combat.";
$l_news_killedshippod  		 = "[target]'s ship was destroyed in ship to ship combat with [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsofapodheadline		 ="[target]'s ship was destroyed while sofa attacking a planet.";
$l_news_killedsofapod  		 = "[target]'s ship was destroyed while sofa attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovapodheadline		 ="[target]'s ship was destroyed during a nova attack.";
$l_news_killednovapod  		 = "[target]'s ship was destroyed by [killer] during a nova bomb attack today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovabackfirepodheadline		 ="[target]'s ship was destroyed from a nova backfire.";
$l_news_killednovabackfirepod  		 = "[target]'s ship was destroyed when their nova bomb backfired today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsectormissilepodheadline		 ="[target]'s ship was destroyed by a Sector Missile.";
$l_news_killedsectormissilepod 		 = "[target]'s ship was destroyed when a Sector Missile from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killhunterprobepodheadline		 ="[target]'s ship was destroyed by a Hunter Probe.";
$l_news_killedhunterprobepod 		 = "[target]'s ship was destroyed when a Hunter Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killtrapprobepodheadline		 ="[target]'s ship was destroyed by a Sentry Trap Probe.";
$l_news_killedtrapprobepod 		 = "[target]'s ship was destroyed when a Sentry Trap Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline		 ="[name] has been promoted to [rank]";
$l_news_promoted 		 = "The Federation is pleased to announce the promotion of [name] to the rank of [rank].";

$l_news_demotedheadline		 ="[name] has been demoted to [rank]";
$l_news_demoted 		 = "The Federation regrets to announce the demotion of [name] to the rank of [rank].";

$l_news_namechangedheadline		 ="[oldname] changed name to [newname]";
$l_news_namechanged 		 = "[oldname] applied to the Federation Review Board to change their name to [newname].  The Federation has granted the name change.  From this day forward [oldname] shall now be known as [newname].  All ships and planets should update their records immediately.";

$l_news_found_planets_short	 = "Federation Survey: [found_planets] new planets located.";
$l_news_found_planets	 = "Federation Survey Scouts have located [found_planets] new planets in recently discovered sectors.";

$l_news_new_ports_short	 = "Federation Survey: [new_ports] new ports constructed.";
$l_news_new_ports	 = "Federation Engineers have constructed [new_ports] new ports in recently discovered sectors.";

$l_news_addedsectors_short	 = "Federation Survey: [addedsectors] sectors discovered.";
$l_news_addedsectors	 = "Federation Survey Scouts have discovered [addedsectors] new sectors.  Caution is advised.";

$l_news_artifactheadline		 ="[playername] completed [artifact]";
$l_news_artifact 		 = "[playername] has found all of the pieces of the [artifact] and has all of the power it can provide.";

$l_news_artifactfoundheadline		 ="[playername] found [artifact] piece";
$l_news_artifactfound 		 = "[playername] has found one of the pieces of the [artifact] and needs [pieces] more [piece].";

?>