<?php
$l_nav_title		 = "Ordinateur de bord";
$l_nav_nocomp		 = "L'ordinateur de bord n'est pas disponible";
$l_nav_query		 = "Entrez le sector que vous voudriez atteindre: ";
$l_nav_pathfnd		 = "Chemin trouvé:";
$l_nav_answ1		 = "Vous utiliserez";
$l_nav_answ2		 = "tours pour atteindre ce secteur.";
$l_nav_proper            = "You need to upgrade your Fighter Bay technology before your fighters can find a warp route for that distance.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
