<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] a touché [chm_roll] mines dans le secteur [chm_sector].";
$l_chm_youlostminedeflectors    = "Vous perdez [chm_roll] déflecteurs.";
$l_chm_youlostallminedeflectors = "Vous perdez tous vos déflecteurs.";
$l_chm_youhadnominedeflectors  = "Vous n'aviez aucun déflecteur.";
$l_chm_yourshieldshitforminesdmg        = "Vos boucliers sont touchés pour [chm_mines_left] points de dommage.";
$l_chm_yourshieldsaredown       = "Vos boucliers sont tombés!";
$l_chm_youlostallyourshields    = "Vous avez perdu tous vos boucliers!";
$l_chm_yourarmorhitforminesdmg  = "Votre armure a été touchée pour [chm_mines_left] points de dommage.";
$l_chm_yourhullisbreached       = "Votre coque a été pénétrée!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] a été détruit par vos mines dans le secteur [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Votre vaisseau a été détruit!";
$l_chm_luckescapepod    = "Heureusement vous aviez un module de secours!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
