<?php
$l_sf_attacking = "Les défenses de secteur vous attaquent!<BR>";
$l_sf_destfight = "Vos rayons détruisent [lost] intercepteurs<BR>";
$l_sf_destfightb = "Vos rayons détruisent [lost] intercepteurs<BR>";
$l_sf_torphit = "Les torpilles touchent:";
$l_sf_destfightt = "Vos torpilles ont détruit [lost] intercepteurs<BR>";
$l_sf_fighthit = "Les intercepteurs attaquent:";
$l_sf_destfightall = "Vous détruisez tous les intercepteurs.<BR>";
$l_sf_destfightt2 = "Vous détruisez [lost] intercepteurs.<BR>";
$l_sf_lostfight = "Vous perdez tous vos intercepteurs.<BR>";
$l_sf_lostfight2 = "Vous perdez [lost] intercepteurs.<BR>";
$l_sf_armorbreach = "Votre armure a été traversée!<BR>";
$l_sf_armorbreach2 = "Votre armure est touchée pour [lost] points de dommage.<BR>";
$l_sf_sendlog = "[player] a détruit [lost] intercepteurs en défense dans le secteur [sector].";
$l_sf_lreport = "Vous avez perdu [armor] points d'armure, [fighters] intercepteurs et avez utilisé [torps] torpilles.<BR><BR>";
$l_sf_shipdestroyed = "Votre vaisseau a été détruit!<BR><BR>";
$l_sf_sendlog2 = "Les intercepteurs en défense dans le secteur [sector] ont détruit [player].";
$l_sf_escape = "Heureusement vous aviez un module de secours!<BR><BR>";

$l_sf_fnoattack		 = " isn't sending any fighters to attack your fighters.";
$l_sf_fnoattackt	 = " isn't sending any fighters to attack your torpedoes.";
$l_sf_fnoattacka	 = " isn't sending any fighters to attack your armor.";
$l_sf_flaunchmalf1		 = "Your fighter launching system has malfunctioned.";
$l_sf_flaunchmalf2		 = "You have only been able to launch ";
$l_sf_flaunchmalf3		 = " percent of your fighters.";
$l_sf_fightertorpexg		 = "Fighter to Torpedo/Mine Exchange";
$l_sf_torpfighterexg		 = "Ship Torpedo to Sector Fighter Exchange";
$l_sf_fighterarmorexg		 = "Sector Fighter to Ship Armor Exchange";
$l_sf_tlaunchmalf1		 = "Your torpedo launching system has malfunctioned.";
$l_sf_tlaunchmalf2		 = "You have only been able to launch ";
$l_sf_tlaunchmalf3		 = " percent of your torpedoes.";
$l_sf_bountysd		 = "You have attacked a sector containing a planet that would give you a bounty if you attacked the planet.  The Federation has activated an automatic self-destruct on all of your fighters and torpedoes. Do not attack the sector defenses in this sector again.  You have been warned!";
?>
