<?php
$l_att_title		 = "Attaque de vaisseau";
$l_att_notarg		 = "La cible n'est pas dans ce secteur.";
$l_att_noturn		 = "Vous avez besoin d'au moins un tour pour pouvoir attaquer.";
$l_att_noatt		 = "Il n'est pas permis d'attaquer quelqu'un dans ce secteur.";
$l_att_flee		 = "Le vaisseau ennemi vous échape!";
$l_att_ewd		 = "Le vaisseau est entré d'urgence dans l'hyper-espace quand vous l'avez attaqué!";
$l_att_att		 = "Attaque ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost		 = "a perdu";
$l_att_ylost		 = "Vous avez perdu";
$l_att_sdown		 = " -> Boucliers tombent!";
$l_att_ydown		 = "Vos boucliers sont tombés!";
$l_att_shits		 = " -> Boucliers touchés de";
$l_att_yhits		 = "Vos boucliers sont touchés de";
$l_att_dmg		 = "points de dommage";
$l_att_sarm		 = " -> Armure pénétrée";
$l_att_yarm		 = "Votre armure est pénétrée!";
$l_att_ashit		 = " -> Armure touchée de";
$l_att_ayhit		 = "Votre armure est touchée de";

$l_att_efhit             = "'s fighters are destroyed.";
$l_att_yfhit             = "of your fighters are destroyed.";
$l_att_ethit             = "'s torpedoes are destroyed.";
$l_att_ythit             = "of your torpedoes are destroyed.";
$l_att_of             = "of";
$l_att_lostt             = "lost all torpedoes.";
$l_att_ylostt            = "You lost all torpedoes.";

$l_att_lostf		 = "a perdu tous ses intercepteurs.";
$l_att_ylostf		 = "Vous avez perdu tous vos intercepteurs.";
$l_att_sdest		 = " -> Vaisseau détruit.";
$l_att_espod		 = "Un module de secours a été lancé!";
$l_att_ysalv		 = "Vous récupérez et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits.<BR>Vous gagnez [rating_change] points.";
$l_att_andused		 = "et utilisé";
$l_att_stilship		 = "Vous n'avez pas détruit le vaisseau de [name].";
$l_att_atyou		 = "attacked you";
$l_att_and		 = "et";
$l_att_yshiplost	 = "Votre vaisseau a été détruit!";
$l_att_salv		 = "[name] a récupéré et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits";

$l_att_tnobeams		 = " seams to be out of beam energy.";
$l_att_tnobeamsf		 = " seams to be out of beam energy and cannot attack your fighters.";
$l_att_tnobeamst		 = " seams to be out of beam energy and cannot attack your torpedoes.";
$l_att_tfnoattack		 = " isn't sending any fighters to attack your ship.";
$l_att_tnotorps		 = " seems to be out of torpedoes.";

$l_att_anobeams		 = "You have exhausted your ships beam energy.";
$l_att_anobeamsf		 = "You have exhausted your ships beam energy and cannot attack the enemy fighters.";
$l_att_anobeamst		 = "You have exhausted your ships beam energy and cannot attack the enemy torpedoes.";
$l_att_anofighters		 = "Your ship has exhausted all availible fighters.";
$l_att_anotorps		 = "You have exhausted your availible torpedoes.";
$l_att_loosepod = "Luckily you have an escape pod!";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "is attacking your ship.";

$l_att_luckybeams		 = "Enemy beams overload inflicting";
$l_att_luckyfighters	 = "Enemy fighters make a surprise lightening attack and cause";
$l_att_luckytorps		 = "Enemy torpedoes induce a cascading damage effect causing";
$l_att_luckytimes		 = "times the normal damage!";
?>
