<?php
$l_novabomb_title             = "Warp Link Nova Bomb";
$l_novabomb_turns            = "The Nova Bomb requires atleast 50 turns to fire.";
$l_novabomb_query             = "Nova Bomb Sector are you sure?";
$l_novabomb_yes           = "Yes Nova Bomb sector ";
$l_novabomb_question             = " to Nova Bomb sector ";
$l_novabomb_success             = " has been Nova Bombed!";
$l_novabomb_mines            = "Destroyed [mines] sector Mines.";
$l_novabomb_fighters            = "Destroyed [fighters] sector Fighters.";
$l_novabomb_planetsdamaged            = "Planets damaged by the Nova Bomb";
$l_novabomb_planet            = "Planet ";
$l_novabomb_damage            = " suffered damage from the Nova Bomb.";
$l_novabomb_shipsdamaged            = "Ships damaged by the Nova Bomb";
$l_novabomb_ship            = "Starship ";
$l_novabomb_novaexplode   ="Nova Bomb exploded as it was fired and your ship has suffered massive damage.";
$l_novabomb_novaexplode2   ="Nova Bomb exploded as it was fired and your ship was destroyed.";
$l_novabomb_notfedsec   ="Nova Bomb cannot be used on Federation owned sectors.";
?>
