<?php
$l_warp_unlinked	 = "Le secteur cible ([target_sector]) n'a pas de lien à partir de ce secteur.";
$l_warp_forbidtwo	 = "L'utilisation d'un éditeur de lien pour détruire un lien de/vers [target_sector] n'est pas permis.";
$l_warp_removed		 = "Le lien à été détruit, vers";
$l_warp_removedtwo	 = "Le lien à été détruit, de et vers";
$l_warp_nomoney          = "You do not have enough credits to delete the warp link.";
$l_warp_noenergy          = "You do not have enough energy to delete the warp link.";
?>
