<?php
$l_gns_title		 = "Torpille Genesis";
$l_gns_turn		 = "Vous avez besoin d'au moins un tour pour utiliser une torpille genesis.";
$l_gns_onplanet		 = "Vous ne pouvez utiliser une torpille genesis à la surface d'une planète.";
$l_gns_full		 = "Ce système solaire est déjà plein.";
$l_gns_planetex          = "There is already a planet in this sector.";
$l_gns_nogenesis	 = "Vous ne possédez aucune torpille genesis.";
$l_gns_forbid		 = "La création d'une planète dans ce secteur n'est pas permise.";
$l_gns_bforbid		 = "Les bases dans se secteur interferent avec la torpille genesis. La création d'une planète est impossible.";
$l_gns_pcreate		 = "Une nouvelle planète est créée.";
$l_sgns_title             = "Use Sector Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "You do not have any sector genesis devices.";
$l_sgns_forbid            = "Creating a sector genesis wormhole in this sector is not permitted.";
$l_sgns_forbid1            = "Creating a sector genesis wormhole a Federation Sector is not permitted.";
$l_sgcreate				= "Create New Sector Genesis Sector";
$l_sgcreatens				= "Create New Sector Genesis Link back to known space";
$l_sgns_forbid2            = "More than [limit] links in SG Sectors are not permitted.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "You do not have enough credits to create a new sector.";
$l_sgns_shipcredits            = "Credits on ship:";
$l_sgns_createcost            = "Cost to create new Sector:";
$l_sgns_complete            = "Normal Space Link Complete";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";


?>
