<?php

// Confirmed common to multiple files:

$l_zname[1]         = "Espace non-exploré";
$l_zname[2]         = "Espace de la Fédération";
$l_zname[3] 		 = "Alliance space";
$l_zname[4]         = "Zonne de Guerre";

$l_nova 		 = "Nova";
$l_nova 		 = "Nova Bomb";
$l_lssd 		 = "Dernier appareil vu";
$l_lss 			 = "Dernier vaissau vu dans ce secteur";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Éditeur de liens";
$l_warp_turn		 = "Vous avez besoin d'au moins un tour pour utiliser un éditeur de liens.";
$l_warp_none		 = "Vous n'avez aucun éditeur de liens.";
$l_warp_forbid		 = "Il n'est pas permis d'utiliser un éditeur de liens.";
$l_warp_nosector	 = "Ce secteur n'existe pas.";
$l_swarp_forbid		 = "Using a Warp Editor to or from SG sectors is not permitted.";
// Not yet confirmed common to multiple files:

$l_yes 			 = "Oui";
$l_no			 = "Non";
$l_here			 = "ici";
$l_submit		 = "Envoyer";
$l_reset		 = "Restaurer";
$l_all			 = "Tout";
$l_max			 = "Max";

$l_trade		 = "Trade";
$l_ore			 = "Métaux";
$l_commodity		 = "Commodity";
$l_commodities           = "Commodities";
$l_organics		 = "Végétaux";
$l_goods		 = "Produits";
$l_energy		 = "Énergie";
$l_colonists		 = "Colons";
$l_credits 		 = "Crédits";
$l_units		 = "unités de ";
$l_special		 = "Spécial";
$l_upgrade_ports         = "Upgrades";
$l_device_ports          = "Devices";
$l_spacedock		 = "Spacedock";
$l_casino		 = "Casino";
$l_spy = "Espions";
$l_dig = "Dignitaries";

$l_cargo		 = "Cargaison";
$l_fighters		 = "Intercepteurs";
$l_mines		 = "Mines";
$l_torps		 = "Torpilles";

$l_none			 = "Aucun";
$l_unnamed		 = "Sans Nom";
$l_name			 = "Nom";
$l_unowned		 = "Libre";
$l_unknown		 = "Inconnu";
$l_clickme 		 = "Cliquer ici";
$l_player  		 = "Joueur";
$l_ship			 = "Vaisseau";
$l_ships		 = "Vaisseaux";
$l_set			 = "Mod";
$l_realspace		 = "Espace Réel";
$l_armorpts		 = "Points d'armure";
$l_links		 = "Liens";
$l_login_email          = "Adresse e-mail:";
$l_submit               = "envoyer";
$l_reset                = "retaurer";
$l_add			 = "Add";
$l_teamforum			 = "Team Forum";
$l_teamships			 = "Team Ships";
$l_tutorial			 = "Tutorial/Help";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Team Icon";
$l_debris			 = "Debris";
$l_localmap			 = "Local Map";
$l_arm_weap              = "Armor & Weapons";
$l_3dmap			 = "3D Galaxy Map";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Space Probes";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Mines/Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Reports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Ship Type";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team defenses";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet defenses";
$l_changeproduction = "Change Production";
$l_galacticarm = "Galactic Arm";
$l_armor		 = "Armor";
$l_news_none		 = "Désolé, aucune nouvelles ajourd'hui.";

$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_neutral       = "Neutral";

$l_global_mmenu			="Cliquez <A HREF=main.php>ici</A> pour retourner au menu principal.";
$l_global_mlogin		="Cliquez <A HREF=index.php>ici</A> pour retourner à l'écran de connection.";
$l_global_needlogin		="Vous devez vous connecter, cliquez <A HREF=index.php>ici</A>.";
$l_global_died			="Vous êtes mort! <a href=log.php>Voici</a> ce qui vous est arrivé<BR><BR>Meilleure chance la prochaine fois!";
$l_global_warzone		="La zone est maintenant une Zone de Guerre!";
$l_global_nzone			="La zone est maintenant une Zone Neutre.";
$l_global_team			="La zone appartient maintenant à l'alliance";
$l_global_player		="La zone appartient maintenant au joueur";
$l_global_nochange      ="Zone ownership didn't change"; //TODO Translate it, please
$l_insignia[0]          = "1c.png";
$l_insignia[1]          = "2c.png";
$l_insignia[2]          = "3c.png";
$l_insignia[3]          = "4c.png";
$l_insignia[4]          = "o-1.png";
$l_insignia[5]          = "o-2.png";
$l_insignia[6]          = "o-3.png";
$l_insignia[7]          = "o-4.png";
$l_insignia[8]          = "o-5.png";
$l_insignia[9]          = "o-6.png";
$l_insignia[10]         = "o-7.png";
$l_insignia[11]         = "o-8.png";
$l_insignia[12]         = "o-9.png";
$l_insignia[13]          = "o-10.png";
$l_insignia[14]          = "o-11.png";
$l_insignia[15]          = "o-12.png";
$l_insignia[16]          = "o-13.png";
$l_insignia[17]          = "o-14.png";
$l_insignia[18]          = "o-15.png";
$l_insignia[19]          = "o-16.png";

$l_insignia_name[0]           = "Spaceman Recruit";
$l_insignia_name[1]           = "Spaceman Apprentice";
$l_insignia_name[2]           = "Spaceman";
$l_insignia_name[3]           = "Petty Officer Third Class";
$l_insignia_name[4]           = "Petty Officer Second Class";
$l_insignia_name[5]           = "Petty Officer First Class";
$l_insignia_name[6]           = "Chief Petty Officer";
$l_insignia_name[7]           = "Senior Chief Petty Officer";
$l_insignia_name[8]           = "Master Chief Petty Officer";
$l_insignia_name[9]           = "Ensign";
$l_insignia_name[10]          = "Lieutenant Junior Grade";
$l_insignia_name[11]          = "Lieutenant";
$l_insignia_name[12]          = "Lieutenant Commander";
$l_insignia_name[13]          = "Commander";
$l_insignia_name[14]          = "Captain";
$l_insignia_name[15]          = "Rear Admiral (lower half)";
$l_insignia_name[16]          = "Rear Admiral (upper half)";
$l_insignia_name[17]          = "Vice Admiral";
$l_insignia_name[18]          = "Admiral";
$l_insignia_name[19]          = "Fleet Admiral";

$l_main_title 		 = "Menu Principal";
$l_main_warpto = "Hyper-espace";
$l_main_autoroute        = "Autoroute to";
$l_main_rs_to            = "RSMove to";
$l_main_other            = "Autre";
$l_main_shipyard1        = "Achat de vaissaux";
$l_main_shipyard2        = "Acceder à l' ";
$l_traderoutes		 = "Commerce";
$l_trade_control	 = "Modifier";
$l_youhave 		 = "Vous avez ";
$l_turns_used		 = "Tours utilisés: ";
$l_turns_have		 = "Tours disponibles: ";
$l_score		 = "Points: ";
$l_sector		 = "Secteur";
$l_help			 = "Aide";
$l_faq		         = "FAQ";
$l_feedback		 = "Commentaires";
$l_forums		 = "Forums";
$l_logout		 = "Quitter";
$l_commands		 = "Commandes";
$l_command_no		 = "Commande non disponible.";
$l_devices		 = "Appareils";
$l_planets		 = "Planètes";
$l_log			 = "Journal";
$l_sector_def		 = "Défenses";
$l_defense		 = "Défenses";
$l_read_msg		 = "Lire Messages";
$l_send_msg		 = "Écrire Messages";
$l_rankings		 = "Rangs";
$l_teams		 = "Alliances";
$l_ohno			 = "Auto-Destruction";
$l_options		 = "Options";
$l_navcomp		         = "Ordinateur";
$l_incompletemove 	 = "Vous n'avez pas complété votre dernier déplacement.";
$l_clicktocontinue	 = "Cliquez ici pour continuer";
$l_toplanetmenu   	 = "Pour aller au menu de planète.";
$l_nonexistant_pl	 = "Sur une planète qui n'existe pas???";
$l_abord		 = ", à bord du ";
$l_messages_wait	 = " Messages qui vous attendent.";
$l_no_warplink		 = "Aucun liens";
$l_scan			 = "sonder";
$l_fullscan		 = "Sonder tout";
$l_port			 = "Port";
$l_tradingport		 = "Port commercial";
$l_planet_in_sec	 = "Planètes dans le secteur ";
$l_ships_in_sec		 = "Autres vaisseaux dans le secteur ";
$l_sector_0		 = "Il y a tellement de déplacements dans Sol que vous ne pouvez distinguer les vaisseaux entre eux!";
$l_map                   = "Carte";
$l_autotrade				 = "Autotrades";
$l_onboard				 = "onboard a";
$l_classship = "class ship";
$l_traveled = "traveled to sector";
$l_max_planets = "Maximum habital planets";
$l_block_msg              = "Block Messages";
$l_probe = "Probes";
$l_sectorinfo               = "Sector Info";
$l_add_note="Add Note";
$l_view_note="View";
$l_notes="Notes";
$l_global_limitreached="You have reached the limit for the amount of time you are allowed to be online each day.  Log in again tomorrow after midnight.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Stored Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader's Lobby";

$l_common_prev="Previous Page";
$l_common_next="Next Page";
$l_common_totalpages="Total Pages";
$l_common_selectpage="Select Page: ";
$l_common_page="Page: ";
$l_templatechange = "Would you like to keep this Template?";

$l_im_fed_bounty = "The Federation has placed a bounty on you for attacking such a low ranked player.  The Federation will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_fed_bounty_title = "Federation placed a Bounty on you!";
$l_im_alliance_bounty = "The Alliance has placed a bounty on you for attacking such a low ranked player.  The Alliance will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_alliance_bounty_title = "Alliance placed a Bounty on you!";
$l_instant_messages_waiting = "You have [count] messages waiting for you.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Filled: ";
$l_hold_space_free = "Holds Empty: ";
$l_port_buys = "Port Buys: ";

?>
