<?php
$l_new_pwis              = "Votre mot de passe est";
$l_new_title2			= "Créer un nouveau joueur Phase Deux";
$l_new_closed_message		="La partie est fermée pour tournoi";
$l_new_blank			="E-mail, nom du vaisseau et nom du joueur ne peuvent être vides.";
$l_new_inuse			="L'adresse e-mail est déjà en utilisation.";
$l_new_4gotpw1			="Si vous avez oublié votre mot de passe,";
$l_new_4gotpw2			="pour qu'il soit envoyé à votre adresse e-mail.";
$l_new_inusechar		="Le nom de joueur $character est déjà en utilisation.";
$l_new_inuseship		="Le nom de vaisseau $shipname est déjà en utilisation.";
$l_new_pwsent			="Le mot de passe a été envoyé à [username].";
$l_new_login			="pour aller à l'écran de connection.";
$l_new_err			="S'il vous plaît cliquez <a href=new_player.php>ici</a> pour réessayer.";
$l_new_topic			="Mot de passe pour Blacknova Traders";
$l_new_message			="Salutations,\n\nQuelqu'un avec l'ip $ip a demandé que votre mot de passe pour Blacknova Traders soit envoyé à cette adresse.\n\nVotre mot de passe est: [pass]\n\nMerci\n\nL'équipe de Blacknova Traders.";
$l_new_invalidemail             = "Invalid Email Address.";
$l_new_tutorial = "Click here to read the Mini-Tutorial before logging into the game.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login             = "to go to the login screen.";
$l_new_charis = "Your character name is";
$l_new_forgotpw = "Forgot your password?";
$l_new_similar_inusechar = "Your character name sounds too similar to [character], a name already in use.";
$l_new_similar_inuseship = "Your ship name sounds too similar to [shipname], a name already in use.";
?>
