<?php
$l_login_sclosed		= "Le serveur est fermé";
$l_login_closed_message		="Le serveur est fermé jusqu'à nouvel ordre.";
$l_login_title2			="Phase deux de la connection";
$l_login_banned			="<b>Vous avez été bannis de ce serveur par l'administrateur. La prochaine fois, conduisez-vous mieux</b>";
$l_login_died			="Votre vaisseau a été détruit, mais votre module de secours vous a sauvé vous ainsi que votre équipage.  Cliquez <A HREF=main.php>ici</A> pour recommencer avec un nouveau vaisseau.";
$l_login_newbie			="À cause du degré de ce crime contre vous, la Fédération a gracieusement accepté de vous cloner. Malheureusement, même en cet âge, les nouveaux clones ne peuvent avoir de propriété, sauf les besoins essentiels. Vous aurez un vaisseau de base et quelque crédits pour commencer une nouvelle vie. Espérons qu'elle sera meilleure que l'ancienne.";
$l_login_newlife		="Cliquez <A HREF=main.php>ici</A> pour continuer vers une nouvelle vie.";
$l_login_looser			="Vous n'aviez pas de module de secours, donc vous avez péri.<BR><BR> Meilleure chance la prochaine fois...";
$l_login_4gotpw1		= "Le mot de passe que vous avez entré est incorrect.<BR><BR>  Si vous avez oublié votre mot de passe, ";
$l_login_4gotpw2		= "pour le recevoir par e-mail.<BR><BR>  Sinon,";
$l_login_4gotpw3		= "pour essayer encore une fois.  La tentative a été enregistrée, de l'ip";
$l_login_noone			= "Ce joueur n'existe pas! - Créer un nouveau joueur <A HREF=new_player.php>ici</A>.";
$l_login_diedincident			= "You have died in a horrible incident.";
$l_login_blackbox			= " is the blackbox information that was retrieved from your ships wreckage.";
$l_new_login             = "to go to the login screen.";
$l_login_playerlimit		= "The server has reached the maximum number of players it supports.  Please try logging in at a later time.";                
?>
