<?php
$l_warp_linkto		 = "Il y a des liens de ce secteur vers";
$l_warp_nolink		 = "Il n'y a aucun lien sortant de ce secteur.";
$l_warp_query		 = "Vers quel secteur voudriez-vous créer un lien?";
$l_warp_oneway		 = "Sens unique?";
$l_warp_dest		 = "Vous pouvez aussi détruire un lien vers ce secteur";
$l_warp_destquery	 = "Vers quel secteur voudriez-vous détruire le lien?";
$l_warp_bothway		 = "Deux sens";
$l_warp_create          = "Create a warp link between Sector: ";
$l_warp_andsector          = " and Sector: ";
$l_warp_distance          = " with a distance of ";
$l_warp_lightyears          = " lightyears";
$l_warp_delete          = "Delete warp link between Sector: ";
$l_warp_costcreate          = "Cost to create:";
$l_warp_costdelete          = "Cost to delete:";
$l_warp_costenergy          = "Energy needed: ";
$l_warp_twoerror	 = "L'utilisation d'un éditeur de lien pour créer un lien vers [target_sector] n'est pas permis.";
?>
