<?php
$l_login_title			= "Connection";
$l_login_pw			= "Mot de passe:";
$l_login_chooseres		= "La résolution de votre écran n'a pu être déterminée. Veuillez choisir le plus près:";
$l_login_newp			= "Si vous êtes un nouveau joueur, cliquez <A HREF=\"new_player.php\">ici</A>.";
$l_login_prbs			= "Problèmes?";
$l_login_emailus		= "Écrivez nous";
$l_login_forgot_pw		= "Vous avez oublier votre mot de passe? Laissez le vide et apuyez sur connecter.";
$l_login_settings 		= "Paramètres de la partie";
$l_login_change			= "Changer";
$l_login_title2			= "Main Login for AATraders";
$l_login_reset1			= "No Reset Scheduled";
$l_login_reset2			= "Scheduled Reset: ";
$l_login_reset3			= "Sched Reset: ";
$l_login_notice			= "Important Notice:";
$l_login_endadminnews			= "End of Admin News";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
