<?php
$l_pre_title = "Avakosmose kiirvalikud";
$l_pre_exceed = "Kiirvalik [preset] &uuml;letab universumi maksimaalset suurust [sector_max]. Kiirvalikuid ei salvestatud.<BR><BR>";
$l_pre_set = "Kiirvalikuks";
$l_pre_save = "Salvesta";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
