<?php
$l_warp_unlinked      = "Sihtpunktist (sektor [target_sector]) ei ole varp-koridori siia sektorisse.";
$l_warp_forbidtwo     = "Varp-koridori m&otilde;lema suuna h&auml;vitamine sektoriga [target_sector] ei ole lubatud.";
$l_warp_removed       = "H&auml;vitati varp-koridor sektorisse";
$l_warp_removedtwo    = "H&auml;vitati m&otilde;lemasuunaline varp-koridor sektoriga";
$l_warp_nomoney          = "You do not have enough credits to delete the warp link.";
$l_warp_noenergy          = "You do not have enough energy to delete the warp link.";
?>
