<?php
$l_sf_attacking     = "Sektori kaitse h&auml;vitajad r&uuml;ndasid Sind!<BR>";
$l_sf_destfight     = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_destfightb    = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_torphit       = "Torpeedod tulistati v&auml;lja:";
$l_sf_destfightt    = "Su torpeedod purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_fighthit      = "H&auml;vitajad r&uuml;ndasid:";
$l_sf_destfightall  = "Sa purustasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_destfightt2   = "Sa purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_lostfight     = "Sa kaotasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_lostfight2    = "Sa kaotasid [lost] h&auml;vitajat.<BR>";
$l_sf_armorbreach   = "Su soomus on purustatud!<BR>";
$l_sf_armorbreach2  = "Su soomus sai [lost] punkti ulatuses vigastada.<BR>";
$l_sf_sendlog       = "[player] purustas [lost] sektori kaitse h&auml;vitajat sektoris [sector].";
$l_sf_lreport       = "Sa kaotasid [armor] soomusepunkti, [fighters] h&auml;vitajat ja kasutasid &auml;ra [torps] torpeedot.<BR><BR>";
$l_sf_shipdestroyed = "<B>Su laev on purustatud!</B><BR><BR>";
$l_sf_sendlog2      = "Sektori kaitse h&auml;vitajad purustasid m&auml;ngija [player] sektoris [sector].";
$l_sf_escape        = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!<BR><BR>";

$l_sf_fnoattack		 = " isn't sending any fighters to attack your fighters.";
$l_sf_fnoattackt	 = " isn't sending any fighters to attack your torpedoes.";
$l_sf_fnoattacka	 = " isn't sending any fighters to attack your armor.";
$l_sf_flaunchmalf1		 = "Your fighter launching system has malfunctioned.";
$l_sf_flaunchmalf2		 = "You have only been able to launch ";
$l_sf_flaunchmalf3		 = " percent of your fighters.";
$l_sf_fightertorpexg		 = "Fighter to Torpedo/Mine Exchange";
$l_sf_torpfighterexg		 = "Ship Torpedo to Sector Fighter Exchange";
$l_sf_fighterarmorexg		 = "Sector Fighter to Ship Armor Exchange";
$l_sf_tlaunchmalf1		 = "Your torpedo launching system has malfunctioned.";
$l_sf_tlaunchmalf2		 = "You have only been able to launch ";
$l_sf_tlaunchmalf3		 = " percent of your torpedoes.";
$l_sf_bountysd		 = "You have attacked a sector containing a planet that would give you a bounty if you attacked the planet.  The Federation has activated an automatic self-destruct on all of your fighters and torpedoes. Do not attack the sector defenses in this sector again.  You have been warned!";
?>
