<?php
$l_login_title        ="Logi sisse";
$l_login_pw           ="Parool:";
$l_login_chooseres    ="Ei suuda m&auml;&auml;rata Su ekraani resolutsiooni. Palun vali l&auml;hedasim:";
$l_login_newp         = "Kui Sa oled uus m&auml;ngija, vajuta <A HREF=\"new_player.php\">siia</A>.";
$l_login_prbs         = "Probleemid?";
$l_login_emailus      = "Kirjuta meile.";
$l_login_forgot_pw    = "Unustasid oma parooli? J&auml;ta see lahter t&uuml;hjaks ja vajuta 'Logi sisse'.";
$l_login_settings     = "M&auml;ngu parameetrid";
$l_login_change       = "Muuda";
$l_login_title2			= "Main Login for AATraders";
$l_login_reset1			= "No Reset Scheduled";
$l_login_reset2			= "Scheduled Reset: ";
$l_login_reset3			= "Sched Reset: ";
$l_login_notice			= "Important Notice:";
$l_login_endadminnews			= "End of Admin News";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
