<?php
$l_att_title     = "Laeva r&uuml;ndamine";
$l_att_notarg     = "Sihtm&auml;rk ei ole selles sektoris.";
$l_att_noturn     = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et r&uuml;nnata.";
$l_att_noatt     = "Selles sektoris ei tohi kedagi r&uuml;nnata.";
$l_att_flee      = "Sihtm&auml;rk lendas eest &auml;ra!";
$l_att_ewd       = "Sihtm&auml;rk kasutas h&auml;daabi varpi!";
$l_att_att       = "R&uuml;ndad ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost      = "kaotas";
$l_att_ylost     = "Sa kaotasid";
$l_att_sdown     = " energiakilp on purustatud!";
$l_att_ydown     = "Su energiakilp on purustatud!";
$l_att_shits     = " energiakilp sai vigastada";
$l_att_yhits     = "Su energiakilp sai vigastada";
$l_att_dmg       = "punkti ulatuses";
$l_att_sarm      = " soomus on t&auml;ielikult purustatud!";
$l_att_yarm      = "Su laeva soomus on t&auml;ielikult purustatud!";
$l_att_ashit     = " soomus sai vigastada";
$l_att_ayhit     = "Su soomus sai vigastada";

$l_att_efhit             = "'s fighters are destroyed.";
$l_att_yfhit             = "of your fighters are destroyed.";
$l_att_ethit             = "'s torpedoes are destroyed.";
$l_att_ythit             = "of your torpedoes are destroyed.";
$l_att_of             = "of";
$l_att_lostt             = "lost all torpedoes.";
$l_att_ylostt            = "You lost all torpedoes.";

$l_att_lostf     = "kaotas k&otilde;ik h&auml;vitajad.";
$l_att_ylostf    = "Sa kaotasid k&otilde;ik h&auml;vitajad.";
$l_att_sdest     = " laev on h&auml;vitatud!";
$l_att_espod     = "H&auml;vivast laevast eraldus p&auml;&auml;stekapsel.";
$l_att_ysalv             = "You salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits.<BR>Your rating changed by [rating_change] points.";
$l_att_andused   = "ja kasutasid";
$l_att_stilship  = "Sa ei suutnud purustada [name] laeva.";
$l_att_atyou     = "r&uuml;ndas Sind";
$l_att_and       = "ja";
$l_att_yshiplost = "Su laev on purustatud!";
$l_att_salv              = "[name] salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits";
$l_att_loosepod	 = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";

$l_att_tnobeams		 = " seams to be out of beam energy.";
$l_att_tnobeamsf		 = " seams to be out of beam energy and cannot attack your fighters.";
$l_att_tnobeamst		 = " seams to be out of beam energy and cannot attack your torpedoes.";
$l_att_tfnoattack		 = " isn't sending any fighters to attack your ship.";
$l_att_tnotorps		 = " seems to be out of torpedoes.";

$l_att_anobeams		 = "You have exhausted your ships beam energy.";
$l_att_anobeamsf		 = "You have exhausted your ships beam energy and cannot attack the enemy fighters.";
$l_att_anobeamst		 = "You have exhausted your ships beam energy and cannot attack the enemy torpedoes.";
$l_att_anofighters		 = "Your ship has exhausted all availible fighters.";
$l_att_anotorps		 = "You have exhausted your availible torpedoes.";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "is attacking your ship.";

$l_att_luckybeams		 = "Enemy beams overload inflicting";
$l_att_luckyfighters	 = "Enemy fighters make a surprise lightening attack and cause";
$l_att_luckytorps		 = "Enemy torpedoes induce a cascading damage effect causing";
$l_att_luckytimes		 = "times the normal damage!";
?>
