<?php
$l_warp_linkto     = "Siit sektorist v&auml;ljuvad varp-koridorid j&auml;rgmistesse sektoritesse:";
$l_warp_nolink     = "Sellest sektorist ei v&auml;lju &uuml;htegi varp-koridori.";
$l_warp_query     = "Millisesse sektorisse Sa soovid luua varp-koridori?";
$l_warp_oneway     = "&Uuml;hesuunalist";
$l_warp_dest     = "Sa v&otilde;id ka h&auml;vitada varp-koridore.";
$l_warp_destquery   = "Millise sektori varp-koridori Sa h&auml;vitada soovid?";
$l_warp_bothway     = "M&otilde;lemad suunad";
$l_warp_create          = "Create a warp link between Sector: ";
$l_warp_andsector          = " and Sector: ";
$l_warp_distance          = " with a distance of ";
$l_warp_lightyears          = " lightyears";
$l_warp_delete          = "Delete warp link between Sector: ";
$l_warp_costcreate          = "Cost to create:";
$l_warp_costdelete          = "Cost to delete:";
$l_warp_costenergy          = "Energy needed: ";
$l_warp_twoerror   = "Kahesuunalise varp-koridori loomine sektoriga [target_sector] ei ole lubatud.";
?>
