<?php
$l_chm_hehitminesinsector          = "[chm_playerinfo_character_name] p&otilde;rkas vastu [chm_roll] miini sektoris [chm_sector].";
$l_chm_youlostminedeflectors       = "Sa kaotasid [chm_roll] miinit&otilde;rjujat.";
$l_chm_youlostallminedeflectors    = "Sa kaotasid k&otilde;ik oma miinit&otilde;rjujad.";
$l_chm_youhadnominedeflectors      = "Sul polnud &uuml;htegi miinit&otilde;rjujat.";
$l_chm_yourshieldshitforminesdmg   = "Su energiakilp sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourshieldsaredown          = "Su energiakilp l&uuml;litus v&auml;lja!";
$l_chm_youlostallyourshields       = "Sa kaotasid kogu oma energiakilbi!";
$l_chm_yourarmorhitforminesdmg     = "Su soomus sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourhullisbreached          = "Kogu Su soomus on purustatud!";
$l_chm_hewasdestroyedbyyourmines   = "Su miinid purustasid m&auml;ngija [chm_playerinfo_character_name] sektoris [chm_sector].";
$l_chm_yourshiphasbeendestroyed    = "<b>Su laev on purustatud!</b>";
$l_chm_luckescapepod               = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
