<?php
$l_nav_title     = "Pardakompuuter";
$l_nav_nocomp     = "Pardakompuutrit ei saa kasutada";
$l_nav_query     = "Sisesta sektor, kuhu soovid j&otilde;uda: ";
$l_nav_pathfnd     = "Tee leitud";
$l_nav_answ1     = "Sinna sektorisse j&otilde;udmine v&otilde;tab";
$l_nav_answ2     = "k&auml;iku.";
$l_nav_proper            = "You need to upgrade your Fighter Bay technology before your fighters can find a warp route for that distance.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
