<?php
// port.php port_purchase.php
$l_trade		 = "Kauple";
$l_title_port		 = "Sadamas kauplemine";
$l_title_trade		 = "Kauplemine";
$l_sector_war		 = "S&otilde;jaembargo";
$l_war_info		 = "Siin sektoris k&auml;ib s&otilde;da. Sa ei suutnud j&otilde;uda sadamani, kuna Sind segasid vaenutsevad v&auml;ed.";
$l_no_trade		 = "Kauplemine keelatud";
$l_no_trade_out		 = "Selles sadamas ei ole v&otilde;&otilde;rastel kauplemine lubatud";
$l_no_trade_info	 = "Selles sadamas ei ole kauplemine lubatud";
$l_buying		 = "Ostab";
$l_selling		 = "M&uuml;&uuml;b";
$l_commodity		 = "Kaup";
$l_amount		 = "Kogus";
$l_price		 = "Hind";
$l_buy			 = "Osta";
$l_sell			 = "M&uuml;&uuml;";
$l_trade_st_info	 = "Sul on [free_holds] &uuml;hikut vaba ruumi, Sa saad juurde osta [free_power] &uuml;hikut energiat ja Sul on [credits] raha.";
$l_upgrade_port_title    = "T&auml;iustamise sadam";
$l_device_port_title     = "Seadmete sadam";
$l_no_credits		 = "Sul ei ole piisavalt raha";
$l_creds_to_spend	 = "Sul on [credits] raha kulutamiseks.";
$l_cost			 = "Hind";
$l_avail		 = "Saadaval";
$l_profit		 = "Kasum";
$l_current		 = "Hetkel";
$l_current_level         = "Praegune tase";
$l_current_qty		 = "Hetkekogus";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Kui Sa vajad rohkem, siis siin on [igb] ";
$l_ifyouneedplan	 = "Siin on planeedi";
$l_igb_term		 = "IGB pangaterminal";
$l_upgrade		 = "Arenda";
$l_unlimited		 = "Piiramatu";
$l_full			 = "T&auml;is";
$l_equipped		 = "Pardal";
$l_n_a			 = "-";
$l_item			 = "Kaup";
$l_totalcost		 = "Kogumaksumus";
$l_would_dump	         = "Kui Sa soovid k&otilde;ik kolonistid Maale tagasi saata, vajuta ";
$l_noport		 = "Siin ei ole kaubasadamat!";
$l_trade_turnneed	 = "Sul peab olema v&auml;hemalt &uuml;ks vaba k&auml;ik, et kaubelda sadamas v&otilde;i planeedil.";
$l_returnto_port1  = "siia";
$l_returnto_port2        = " Vajuta [port_link], et minna sadama men&uuml;&uuml;sse.";
$l_notenough_cargo	 = "Sul ei ole piisavalt vaba ruumi, et l&otilde;petada tehingut.";
$l_notenough_power	 = "Sul ei ole piisavalt ruumi energiale, et l&otilde;petada tehingut.";
$l_notenough_credits	 = "Sul ei ole piisavalt raha, et l&otilde;petada tehingut.";
$l_notenough_turns	 = "Sul ei ole piisavalt k&auml;ike, et l&otilde;petada tehingut.";
$l_trade_result		 = "Kauplemise tulemused";
$l_trade_complete	 = "Kauplemine l&otilde;petatud";
$l_trade_upgraded = "Uuendatud tasemele ";
$l_trade_added = "lisatud";
$l_trade_installed = "installeeritud";
$l_port_bounty = "Sind ei lasta keskjaama, kui Sinu laeva eest on F&ouml;deratsioon pearaha v&auml;lja pannud.<BR>";
$l_port_bounty2 = "Vajuta <a href=\"port.php?pay=1\">siia</a> et maksta [amount] raha suurune pearaha.";
$l_port_btynotenough = "Sul ei ole piisavalt raha, et maksta [amount] suurust pearaha.<BR>";
$l_port_bountypaid = "Sa maksid pearaha v&auml;lja. Vajuta <a href=\"port.php\">siia</a> et j&auml;tkata.<BR>";
$l_port_loannotrade = "IGB lukustas Su laeva konto, kuna Sa oled laenu tagasi maksmisega hiljaks j&auml;&auml;nud. Sa ei saa enne keskjaamas kaubelda, kui oled oma laenu tagasi maksnud.";
$l_port_returntospecial = "et minna tagasi sadamasse.";
$l_ports_shiplimit = "Minimum Ship class to mount device: ";
$l_ports_needrepair = "Repair";
$l_spacedock_port_title	 = "Spacedock";

$l_ports_needcredits = "You do not have enough credits for this transaction.	The total cost is";
$l_ports_needcredits1 = "credits and you only have";

$l_ports_tradeforbidden = "Trade forbidden";
$l_ports_nooutsiders = "Trading at this port is not allowed for outsiders.";
$l_toprobemenu = "to go to the probe menu.";

$l_bought		 = "You bought";
$l_sold		 = "You sold";
$l_notenough_commodity	 = "You do not have enough [commodity] to complete the transaction.";
$l_exceed_commodity	 = "Number of [commodity] exceeds the supply/demand.  ";
$l_port_shiptoolarge = "Your ship is too large to trade at this port.";

$l_port_hold_unit= "Holds per Unit";

?>
