<?php
$l_gns_title       = "Mateeriatorpeedo kasutamine";
$l_gns_turn        = "Et kasutada mateeriatorpeedot, peab Sul v&auml;hemalt &uuml;ks k&auml;ik olema.";
$l_gns_onplanet    = "Planeedi pinnal olles ei saa nii v&otilde;imast seadet kasutada.";
$l_gns_full        = "Selle sektori t&auml;hes&uuml;steem on juba t&auml;is.";
$l_gns_planetex    = "Selles sektoris on juba planeet.";
$l_gns_nogenesis   = "Sul ei ole &uuml;htegi mateeriatorpeedot.";
$l_gns_forbid      = "Selles sektoris ei ole lubatud mateeriatorpeedot kasutada.";
$l_gns_bforbid     = "Selle sektori baasid ei lase Sul mateeriatorpeedot kasutada.";
$l_gns_pcreate     = "Planeet loodud!";
$l_sgns_title             = "Use Sector Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "You do not have any sector genesis devices.";
$l_sgns_forbid            = "Creating a sector genesis wormhole in this sector is not permitted.";
$l_sgns_forbid1            = "Creating a sector genesis wormhole a Federation Sector is not permitted.";
$l_sgcreate				= "Create New Sector Genesis Sector";
$l_sgcreatens				= "Create New Sector Genesis Link back to known space";
$l_sgns_forbid2            = "More than [limit] links in SG Sectors are not permitted.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "You do not have enough credits to create a new sector.";
$l_sgns_shipcredits            = "Credits on ship:";
$l_sgns_createcost            = "Cost to create new Sector:";
$l_sgns_complete            = "Normal Space Link Complete";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";


?>
