<?php
$l_readm_title       = "Teadete lugemine";
$l_readm_delete      = "Teade kustutatud";
$l_readm_nomessage   = "Sind ei oota &uuml;kski teade...<BR>";
$l_readm_center      = "Teadete keskus";
$l_readm_sender      = "Saatja";
$l_readm_captn       = "Kapten laeval";
$l_readm_del         = "Kustuta";
$l_readm_repl        = "Vasta";
$l_readm_return            = "Click here to return to the main menu";
$l_readm_title2            = "Mail Reader";
$l_readm_delete            = "Delete All";
$l_readm_subject            = "Subject";
$l_readm_quote            = "Quote";
$l_readm_block            = "Block Sender";
$l_readm_alert            = "System Alert";
$l_readm_alertbody            = "Ship Computer";
?>
