<?php
$l_warp_unlinked         = "Указанный сектор ([target_sector]) не имеет гиперперехода из этого сектора.";
$l_warp_forbidtwo        = "Использование исказителя гиперпространства для удаления двустороннего гиперперехода с сектором [target_sector] не разрешено.";
$l_warp_removed          = "Обрезан гиперпереход к сектору";
$l_warp_removedtwo       = "Обрезан двусторонний гиперпереход к сектору";
$l_warp_nomoney          = "You do not have enough credits to delete the warp link.";
$l_warp_noenergy          = "You do not have enough energy to delete the warp link.";
?>
