<?php
$l_move_title            = "Перемещение";
$l_move_turn             = "Вам необходим хотя бы один ход для перемещения.";
$l_move_failed           = "Что-то не так, вы остались стоять на том же месте!";
$l_rs_title              = "Движение";
$l_rs_whichsector        = "До какого сектора хотите добраться?";
$l_rs_insector           = "Вы находитесь в секторе [sector] - а всего их от 1 до [sector_max].";
$l_rs_submit             = "Вычислить";
$l_rs_movetime           = "С такими движками ты пролетишь это расстояние за [triptime] ходов.";
$l_rs_energy             = "Ты соберешь [energy] единиц энергии";
$l_rs_noturns            = "У вас недостаточно ходов для такого перелета.";
$l_rs_engage_link        = "Запустить";
$l_rs_engage             = "У вас [turns] ходов. [engage] двигатели?";
$l_rs_invalid            = "You cannot realspace to that sector from here.";
$l_rs_ready              = "Вы в секторе [sector]. Потрачено [triptime] ходов, собрано [energy] единиц энергии.";
$l_warp_invalid            = "You cannot warp to that sector from here.";
$l_move_unknown = "Unknown Movetype";
?>
