<?php
$l_defense_deploy_title           ="Установить мины и выпустить истребители";
$l_defense_deploy_noturn          ="Для установки орбитальных сил сектора требуется как минимум один ход.";
$l_defense_deploy_nopermit        ="Здесь нельзя устанавливать мины и истребители.";
$l_defense_deploy_nodeploy        ="Нельзя установить мины (истребители) - их тут уже и без ваших дофига.";
$l_defense_deploy_info1           ="Вы находитесь в секторе [sector]. Видно [mines] мин и [fighters] истребителей.";
$l_defense_deploy_info2           ="Готово [mines] мин и [fighters] истребителей";
$l_defense_deploy_deploy          ="Установить";
$l_defense_deploy_deployed        ="Установлены";
$l_defense_deploy_att             ="Атака";
$l_defense_deploy_notorps         ="Недостача ракет.";
$l_defense_deploy_nofighters      ="Дефицит истребителей";
$l_defense_deploy_dmines          ="Установлено [mines] мин.";
$l_defense_deploy_dfighter        ="Deployed [fighters] fighters.";
$l_defense_deploy_max_fighters    ="This sector can support a maximum of [amount] fighters.";
$l_defense_deploy_toomanyfighters ="You have tried to deploy more fighters than the sector can support.";
?>
