<?php
$l_att_title             = "Атаковать корабль.";
$l_att_notarg            = "Цель ушла из зоны поражения.";
$l_att_noturn            = "Вам необходим хотя бы 1 ход для атаки.";
$l_att_noatt             = "Атака в этом секторе запрещена.";
$l_att_flee              = "Цель улетела от Вас!";
$l_att_ewd               = "Враг использовал аварийный гипердвигатель и избежал атаки!";
$l_att_att               = "Атака ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost              = "потеряно";
$l_att_ylost             = "Вы потеряли";
$l_att_sdown             = " (лишился энергощита) энергощит отключен!";
$l_att_ydown             = "Ваш энергощит отключен!";
$l_att_shits             = " энергощит ослаблен на";
$l_att_yhits             = "Ваш энергощит ослаблен на";
$l_att_dmg               = "урон";
$l_att_sarm              = " (лишился брони) броня пробита!";
$l_att_yarm              = "Ваша броня не выдержала!";
$l_att_ashit             = " (понес повреждение брони на) броня была повреждена на";
$l_att_ayhit             = "Ваша броня повреждена на";

$l_att_efhit             = "'s fighters are destroyed.";
$l_att_yfhit             = "of your fighters are destroyed.";
$l_att_ethit             = "'s torpedoes are destroyed.";
$l_att_ythit             = "of your torpedoes are destroyed.";
$l_att_of             = "of";
$l_att_lostt             = "lost all torpedoes.";
$l_att_ylostt            = "You lost all torpedoes.";

$l_att_lostf             = "потерял все истребители.";
$l_att_ylostf            = "Вы потеряли все истребители.";
$l_att_sdest             = " корабль уничтожен.";
$l_att_espod             = "Спасательная капсула запущена!";
$l_att_ysalv             = "Вы захватили и [ship_salvage_rate]% стоимости корабля, что составило [ship_salvage] кредитов.<BR>Ваш рейтинг изменился на [rating_change].";
$l_att_andused           = "и использовал";
$l_att_stilship          = "Вы не уничтожили корабль [name].";
$l_att_atyou             = "атаковал Вас";
$l_att_and               = "и";
$l_att_yshiplost         = "Ваш корабль уничтожен!";
$l_att_salv              = "[name] захватил и [ship_salvage_rate]% стоимости корабля, что составило [ship_salvage] кредитов.";
$l_att_loosepod		 = "К счастью у вас есть спасательная капсула!";

$l_att_tnobeams		 = " seams to be out of beam energy.";
$l_att_tnobeamsf		 = " seams to be out of beam energy and cannot attack your fighters.";
$l_att_tnobeamst		 = " seams to be out of beam energy and cannot attack your torpedoes.";
$l_att_tfnoattack		 = " isn't sending any fighters to attack your ship.";
$l_att_tnotorps		 = " seems to be out of torpedoes.";

$l_att_anobeams		 = "You have exhausted your ships beam energy.";
$l_att_anobeamsf		 = "You have exhausted your ships beam energy and cannot attack the enemy fighters.";
$l_att_anobeamst		 = "You have exhausted your ships beam energy and cannot attack the enemy torpedoes.";
$l_att_anofighters		 = "Your ship has exhausted all availible fighters.";
$l_att_anotorps		 = "You have exhausted your availible torpedoes.";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "is attacking your ship.";

$l_att_luckybeams		 = "Enemy beams overload inflicting";
$l_att_luckyfighters	 = "Enemy fighters make a surprise lightening attack and cause";
$l_att_luckytorps		 = "Enemy torpedoes induce a cascading damage effect causing";
$l_att_luckytimes		 = "times the normal damage!";
?>
