<?php
$l_mail_title            ="Отправить пароль на E-Mail";
$l_mail_noplayer         ="Нет такого игрока! - <a href=new_player.php>Создать нового игрока</a>.";
$l_mail_sent             ="Пароль был выслан";
$l_mail_topic            ="$game_name Пароль";
$l_mail_message          ="Здравствуйте,\n\n Некто с узла $ip запросил пароль к игре $game_name \n\n Ваш пароль: [pass]\n\nСпасибо, что играете у нас.\n\n Администрация $game_name .";
$l_new_login             = "чтобы перейти ко входу в игру.";
$l_mail_failed             ="Password failed to send to";
?>
