<?php
$l_chf_youretreatback    = "¬ы отступили в исходный сектор";
$l_chf_movefailed        = "ѕередвижение не состо€лось.";
$l_chf_thefightersdetectyou     = "»стребители обнаружили вас!";
$l_chf_therearetotalfightersindest      = "¬ секторе находитс€ [chf_total_sector_fighters] истребителей.";
$l_chf_youcanretreat     = "<B>отступить</B> - ќтступление будет стоить дополнительного хода.";
$l_chf_inputfight        = "<B>вступить в бой</B> - вам прийдетс€ уничтожить все истрабители в секторе.";
$l_chf_inputcloak        = "<B>замаскироватьс€</B> - используйте маскировку чтобы истребители вас не засекли.";
$l_chf_go                = "¬ыполн€ть!";
$l_chf_inputrun        = "<B>Attack and Run</B> - You do a lightening attack run and retreat.  But you MAY take some damage during retreat.";
?>
