<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] уничтожил [chm_roll] мин в секторе [chm_sector].";
$l_chm_youlostminedeflectors    = "Вы потеряли [chm_roll] отражателей мин.";
$l_chm_youlostallminedeflectors = "Вы потеряли все отражатели мин.";
$l_chm_youhadnominedeflectors  = "У вас нет отражателей мин.";
$l_chm_yourshieldshitforminesdmg        = "Ваш энергощит ослаблен на [chm_mines_left].";
$l_chm_yourshieldsaredown       = "Ваш энергощит отключен!";
$l_chm_youlostallyourshields    = "Вы лишились энергощита!";
$l_chm_yourarmorhitforminesdmg  = "Ваша броня повреждена на [chm_mines_left].";
$l_chm_yourhullisbreached       = "Ваша броня не выдержала!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] потерпел крушение на минном поле в секторе [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Ваш корабль уничтожен!";
$l_chm_luckescapepod     = "К счастью у вас есть спасательная капсула!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
