<?php
$l_new_pwis              = "Ваш пароль - ";
$l_new_charis            = "Имя вашего чара";
$l_new_title2            = "Вторая фаза содания нового игрока";
$l_new_blank             = "Мыло, название корабля и имя чара должны быть указаны.";
$l_new_inuse             = "Такой адрес [username] уже используется.";
$l_new_forgotpw          = "Забыли свой пароль?";
$l_new_inusechar         = "Имя чара [character] уже используется.";
$l_new_similar_inusechar = "Указанное вами имя слишком схоже с [character], которое уже используется.";
$l_new_inuseship         = "Название корабля [shipname] уже используется.";
$l_new_similar_inuseship = "Указанное вами название слишком схоже с [shipname], которое уже используется.";
$l_new_pwsent            = "Пароль отправлен пользователю [username].";
$l_new_err               = "Хмм, может ещё попыточку";
$l_new_topic             = "Пароль для NGS:TKI";
$l_new_message           = "Здравствуйте,\n\n Некто с узла $ip запросил пароль к игре NGS:TKI \n\n Ваш пароль: [pass]\n\nСпасибо, что играете у нас.\n\n Администрация игры.";
$l_new_invalidemail             = "Invalid Email Address.";
$l_new_tutorial = "Click here to read the Mini-Tutorial before logging into the game.";
$l_new_profile = "If you have a Player Profile, at <a href='http://www.aatraders.com' target='_blank'>www.aatraders.com</a>, you can register this player in the <b>Options</b>. ";
$l_new_login             = "to go to the login screen.";
?>
