<?php
$l_sendm_title           = "Отправить сообщение";
$l_sendm_to              = "Кому";
$l_sendm_from            = "От";
$l_sendm_ally            = "Альянс:";
$l_sendm_subj            = "Тема";
$l_sendm_mess            = "Сообщение";
$l_sendm_send            = "Отправить";
$l_sendm_sent            = "Сообщение отправлено";
$l_sendm_blocked            = " has blocked you from sending messages.";
$l_sendm_blockmanager            = "Message Block Manager";
?>
