<?php
///SPIES
$l_spy_title = "Меню шпионов";
$l_spy = "Шпионы";
$l_spy_disabled = "Шпионы запрешены!";
$l_spy_noturn = "Нужен хотя бы один ход.";
$l_spy_notonboard = "У вас на борту нет подготовленных шпионов.";
$l_spy_ownplanet = "Вы не можете послать шпиона свою планету.";
$l_spy_unownedplanet = "Нельзя послать шпиона на бесхозную планету.";
$l_spy_planetfull = "На планете итак уже [max] шпионов.";
$l_spy_sendtitle = "Внедрение шпиона [spyID] на планету:<BR>Укажите задание шпиона:";
$l_spy_type1 = " Шпион работает только на этой планете.";
$l_spy_type2 = " Шпион проникает на корабль потенциального противника.";
$l_spy_type3 = " Шпион проникает на корабль потенциального противника, и пытается устроиться на другой планете.";
$l_spy_sendbutton = "Постлать на планету";
$l_spy_sendsuccessful = "Шпион высадился на планету и ждет подходящего времени для начала действий.";
$l_spy_sendfailed = "Радары планеты засекли вашего шпиона, т.к. ваша маскировка никуда не годится. Ваш шпион убит.";
$l_spy_noturn2 = "Чтобы отозвать шпиона, нужен хотя бы один ход.";
$l_spy_confirm = "Неужели вам так охота отзывать шпиона [spyID]?";
$l_spy_cleanupplanet = "чтобы очистить планету от вражеских шпионов.";
$l_spy_cleanupship = "Для очистки корабля от вражеских шпионов нажмите";
$l_spy_yourspies = "Ваши шпионы на планете";
$l_spy_sendnew = "Заслать нового шпиона";

$l_spy_codenumber = "Код";
$l_spy_job = "Задание";
$l_spy_percent = "Процент";
$l_spy_move = "Поведение";
$l_spy_action = "Действие";
$l_spy_shipowner = "Владелец корабля";
$l_spy_shipname = "Название корабля";
$l_spy_shiptype = "Класс корабля";
$l_spy_shiplocation = "Положение корабля";
$l_spy_planetowner = "Владелец планеты";
$l_spy_planetname = "Планета";
$l_spy_sector = "Сектор";

$l_spy_moves['none'] = "Остается на месте";
$l_spy_moves['toship'] = "Проникает на корабль";
$l_spy_moves['toplanet'] = "Отправляется на планету";

$l_spy_comeback = "Отозвать";
$l_spy_nospieshere = "You do not have any spies on this planet!";
$l_spy_transferred = "шпионов отправлено";
$l_spy_backonship = "Шпион уже на корабле.";
$l_spy_backfailed = "Шпиона отозвать не удалось.";
$l_spy_changetitle = "Смена поведения шпиона [spyID]:";
$l_spy_occupied = "Ваш шпион [spyID] устроен как [job], на [percent]%.";
$l_spy_dismiss = "Отозвать шпиона?";
$l_spy_changebutton = "Сменить";
$l_spy_changejob = "Change Job or Movement";
$l_spy_linkback = "для входа в меню шпоинов.";
$l_spy_changed1 = "Поведение изменено.";
$l_spy_changed2 = "Шпион отозван.";
$l_spy_changefailed = "Ничего не получилось.";
$l_spy_cleanupplanettitle = "Зачистка вашей планеты от вражеских шпионов:";
$l_spy_notyourplanet = "Это не ваша планета.";
$l_spy_cleanuptext[1] = "Быстрая зачистка. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cleanuptext[2] = "Хорошая зачистка. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cleanuptext[3] = "Операция Вихрь. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cannotcleanupplanet = "У вас всего [turns] ходов, а на планете - [credits] кредов.";
$l_spy_cleanupbutton1 = "Зачистка планеты начата";
$l_spy_cleanupplanettitle2 = "Радары обнаружения врагов на планете включены.";
$l_spy_spyfoundonplanet = "На планете обнаружен шпион [spyID], посланный [player]. Шпион уничтожен.";
$l_spy_spynotfoundonplanet = "Шпионов на планете не обнаружено.";
$l_spy_notenough = "Для начала зачистки недостаточно кредов или ходов.";

$l_spy_cleanupshiptitle = "Зачистка корабля от шпионов:";
$l_spy_notinspecial = "Для начала зачистки корабля отправляйтесь в инструментальный порт.";
$l_spy_cleanupshiptext[1] = "Быстрая зачистка. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cleanupshiptext[2] = "Хорошая зачистка. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cleanupshiptext[3] = "Операция Вихрь. Нужно [creds] кредов и [turns] ходов.";
$l_spy_cannotcleanupship = "У вас всего [turns] ходов и [credits] кредов.";
$l_spy_cleanupbutton2 = "Зачистка корабля начата";
$l_spy_cleanupshiptitle2 = "Радары обнаружения врагов на корабле включены.";
$l_spy_spyfoundonship = "На корабле обнаружен шпион [spyID], посланный [player]. Шпион замочен.";
$l_spy_spynotfoundonship = "Шпионов на корабле не обнаружено. Странно...";

$l_spy_infodeleted = "Сообщение потёрто";
$l_spy_infonotyours = "Читать чужие письма нехорошо!!!";
$l_spy_noinfo = "Ваши шпионы на вражеских кораблях пинают баклуши.";
$l_spy_infotitle = "Ваши шпионы нарыли кое-чего";
$l_spy_time = "Время";
$l_spy_type = "Тип";
$l_spy_info = "Инфа";
$l_spy_datatype[1] = "Планета";
$l_spy_datatext[1] = "В секторе [sector] находится планета [planet] товарища [player].";
$l_spy_delete = "Потереть мессагу";
$l_spy_messages = "и вы увидите всё, что накопали ваши шпионы.";
$l_spy_defaulttitle1 = "Шпионы на кораблях противников";
$l_spy_defaulttitle2 = "Шпионы на планетах вражеских государств";
$l_spy_defaulttitle3 = "Шпионы на своих планетах";
$l_spy_defaulttitle4 = "Шпионы на корабле";

$l_spy_no1 = "На кораблях противников нет ваших шпионов.";
$l_spy_no2 = "На планетах вражеских государтсв нет ваших шпионов.";
$l_spy_no3 = "На ваших планетах нет ваших шпионов.";
$l_spy_no4 = "На корабле нет ваших шпионов.";
$l_spy_nospiesatall = "Шпионов просто нет.";
$l_spy_notknown = "Хто тут? не понял...";

$l_spy_trytitle = "On the planet this spy will try to"; //TODO: Translate it, please

$l_spy_cantsendfeds = "Sorry but Spies cannot be sent to Federation or Independant Planets.";
$l_spy_cantsendteam = "You cannot place Spies on a teammates planet.";
$l_spy_messagesdeleted = "All messages deleted";
$l_spy_deleteall = "Delete All";
$l_spy_onplanet = "Spies on planet";
$l_spy_menu = "to return to Spy Menu.";
?>
