<?php
$l_login_sclosed		= "Сервер закрыт";       
$l_login_closed_message		= "Приходите попозже.";                
$l_login_title2			= "Вторая стадия входа в игру";
$l_login_banned			= "<b>Для вас доступ в игру закрыт администратором. Вы не можете играть больше на этом сервере. Возможно в следующий раз...</b>";
$l_login_died			= "Ваш корабль был уничтожен, но спасательная капсула спасла вас от смерти. Нажмите <A HREF=main.php>здесь</A> для получения нового корабля.";
$l_login_newbie			= "Благодаря вашим заслугам Федерация клонировала ваше тело. К сожалению клон не имеет право на наследство, поэтому вы начнете с маленьким кораблем и небольшой суммой. Надеемся в следующий раз вы будете удачливее.";
$l_login_newlife		= "Нажмите  <A HREF=main.php>здесь</A> чтобы начать новую жизнь.";
$l_login_looser			= "Вы не имели спасательной капсулы, и Федерация отказалась клонировать вас. В вашем доме играет музыка, которой вы не слышите....<BR><BR> Удачи в следующий раз...";
$l_login_4gotpw1		= "Введенный пароль неверен.<BR><BR>  Если вы забыли пароль, ";
$l_login_4gotpw2		= "и он будет выслан вам.<BR><BR>  или,";     
$l_login_4gotpw3		= "чтобы попробовать еще раз. Попытка входа предпринята с узла ";
$l_login_noone			= "Нет такого игрока! - Создайте нового игрока <A HREF=new_player.php>здесь</A>.";
$l_login_diedincident			= "You have died in a horrible incident.";
$l_login_blackbox			= " is the blackbox information that was retrieved from your ships wreckage.";
$l_new_login             = "to go to the login screen.";
$l_login_playerlimit		= "The server has reached the maximum number of players it supports.  Please try logging in at a later time.";                
?>
