<?php
$l_sf_attacking          = "Истребители орбитальных сил атакуют!<BR>";
$l_sf_destfight          = "Ваши пушки уничтожили [lost] истребителей<BR>";
$l_sf_destfightb         = "Ваши пушки уничтожили [lost] истребителей<BR>";
$l_sf_torphit            = "Торпедный залп:";
$l_sf_destfightt         = "Ваши торпеды уничтожили [lost] истребителей<BR>";
$l_sf_fighthit           = "Атака истребителей:";
$l_sf_destfightall       = "Вы уничтожили все истребители.<BR>";
$l_sf_destfightt2        = "Вы уничтожили [lost] истребителей.<BR>";
$l_sf_lostfight          = "Вы потеряли все истребители.<BR>";
$l_sf_lostfight2         = "Вы потеряли [lost] истребителей.<BR>";
$l_sf_armorbreach        = "Ваша броня разрушена!<BR>";
$l_sf_armorbreach2       = "Ваша броня повреждена на [lost].<BR>";
$l_sf_sendlog            = "[player] потерял [lost] орбитальных истребителей в секторе [sector].";
$l_sf_lreport            = "Вы потеряли [armor] брони, [fighters] истребителей и использовали [torps] торпед.<BR><BR>";
$l_sf_shipdestroyed      = "Ваш корабль уничтожен!<BR><BR>";
$l_sf_sendlog2           = "Орбитальные истребители уничтожили [player] в секторе [sector].";
$l_sf_escape             = "Благо у вас была спасательная капсула!<BR><BR>";

$l_sf_fnoattack		 = " isn't sending any fighters to attack your fighters.";
$l_sf_fnoattackt	 = " isn't sending any fighters to attack your torpedoes.";
$l_sf_fnoattacka	 = " isn't sending any fighters to attack your armor.";
$l_sf_flaunchmalf1		 = "Your fighter launching system has malfunctioned.";
$l_sf_flaunchmalf2		 = "You have only been able to launch ";
$l_sf_flaunchmalf3		 = " percent of your fighters.";
$l_sf_fightertorpexg		 = "Fighter to Torpedo/Mine Exchange";
$l_sf_torpfighterexg		 = "Ship Torpedo to Sector Fighter Exchange";
$l_sf_fighterarmorexg		 = "Sector Fighter to Ship Armor Exchange";
$l_sf_tlaunchmalf1		 = "Your torpedo launching system has malfunctioned.";
$l_sf_tlaunchmalf2		 = "You have only been able to launch ";
$l_sf_tlaunchmalf3		 = " percent of your torpedoes.";
$l_sf_bountysd		 = "You have attacked a sector containing a planet that would give you a bounty if you attacked the planet.  The Federation has activated an automatic self-destruct on all of your fighters and torpedoes. Do not attack the sector defenses in this sector again.  You have been warned!";
?>
