<?php
$l_zi_title              = "Информация о секторе";
$l_zi_nexist             = "Эта зона космоса не существует!";
$l_zi_feds               = "Федерация";
$l_zi_traders            = "Alliance Space";
$l_zi_nobody             = "Ничейная зона";
$l_zi_war                = "Contested space";
$l_zi_allow              = "Разрешено";
$l_zi_notallow           = "Запрещено";
$l_zi_limit              = "Только владельцу и альянсу";
$l_zi_ul                 = "Неограничено";
$l_zi_control            = "You are in control of this zone";
$l_zi_tochange           = "чтобы изменить законы.";
$l_zi_owner              = "Хозяин сектора";
$l_zi_maxhull            = "Максимально разрешенный средний технический уровень";
?>
