<?php

// Confirmed common to multiple files:

$l_zname[1] 		 = "Бесхозный сектор";
$l_zname[2] 		 = "Федерация";
$l_zname[3] 		 = "Alliance space";
$l_zname[4] 		 = "Военная зона";

$l_nova 		 = "Nova";
$l_nova 		 = "Nova Bomb";
$l_lssd 		 = "Анализатор квантового следа";
$l_lss 			 = "Последний замеченный в секторе корабль";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Запуск исказителя гиперпространственных переходов";
$l_warp_turn		 = "Для использования исказителя необходимо иметь хотябы один ход.";
$l_warp_none		 = "У вас нет исказителей гиперпространственных переходов.";
$l_warp_forbid		 = "Использование исказителей в этом секторе запрещено.";
$l_warp_nosector	 = "Такой сектор не существует.";
$l_swarp_forbid		 = "Using a Warp Editor to or from SG sectors is not permitted.";
// Not yet confirmed common to multiple files:

$l_yes 			 = "Да";
$l_no			 = "Нет";
$l_here			 = "здесь";
$l_submit		 = "Подтвердить";
$l_reset		 = "Сброс";
$l_all			 = "Все";
$l_max			 = "Max";

$l_trade		 = "Trade";
$l_ore			 = "Руда";
$l_commodity		 = "Commodity";
$l_commodities		 = "Сырье";
$l_organics		 = "Органика";
$l_goods		 = "Товары";
$l_energy		 = "Энергия";
$l_colonists		 = "Колонисты";
$l_credits 		 = "Кредиты";
$l_units		 = "единиц ";
$l_special		 = "Особый";
$l_upgrade_ports	 = "Модернизация";
$l_device_ports		 = "Инструментальный";
$l_spacedock		 = "Spacedock";
$l_casino		 = "Casino";
$l_spy = "Шпионы";
$l_dig = "Dignitaries";

$l_cargo		 = "Груз";
$l_fighters		 = "Истребители";
$l_mines		 = "Мины";
$l_torps		 = "Торпеды";

$l_none			 = "Нет";
$l_unnamed		 = "Безымянный";
$l_name			 = "Имя";
$l_unowned		 = "Бесхозный";
$l_unknown		 = "Неизвестный";
$l_clickme 		 = "Нажмите здесь";
$l_player  		 = "Игрок";
$l_ship			 = "Корабль";
$l_ships		 = "Корабли";
$l_set			 = "изменить";
$l_realspace		 = "Космос";
$l_armorpts		 = "брони";
$l_links		 = "Переходы";
$l_login_email          = "Адрес E-mail:";
$l_add			 = "Add";
$l_teamforum			 = "Team Forum";
$l_teamships			 = "Team Ships";
$l_tutorial			 = "Tutorial/Help";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Team Icon";
$l_debris			 = "Debris";
$l_localmap			 = "Local Map";
$l_arm_weap              = "Armor & Weapons";
$l_3dmap			 = "3D Galaxy Map";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Space Probes";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Mines/Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Reports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Ship Type";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team defenses";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet defenses";
$l_changeproduction = "Change Production";
$l_galacticarm = "Galactic Arm";
$l_armor		 = "Armor";
$l_news_none             = "Сегодня у новостей выходной.";

$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_neutral       = "Neutral";

$l_global_mmenu          ="Нажмите <A HREF=main.php>здесь</A> для возврата на главную страницу.";
$l_global_mlogin         ="Нажмите <A HREF=index.php>здесь</A> чтобы вернутся ко входу в игру.";
$l_global_needlogin      ="Вам необходимо войти в игру, нажмите <A HREF=index.php>здесь</A>.";
$l_global_died           ="Игрок МЕРТВ! Нажмите <a href=log.php>здесь</a> чтобы вскрыть черный ящик.<BR><BR>Удачи в следующий раз!";
$l_global_warzone        ="Этот сектор теперь - военная зона!";
$l_global_nzone          ="Этот сектор теперь нейтральный.";
$l_global_team           ="Этот сектор теперь находится под управлением альянса";
$l_global_player         ="Этот сектор теперь контролируется игроком";
$l_global_nochange       ="Принадлежность сектора не изменилась";
$l_insignia[0]           = "1c.png";
$l_insignia[1]           = "2c.png";
$l_insignia[2]           = "3c.png";
$l_insignia[3]           = "4c.png";
$l_insignia[4]           = "o-1.png";
$l_insignia[5]           = "o-2.png";
$l_insignia[6]           = "o-3.png";
$l_insignia[7]           = "o-4.png";
$l_insignia[8]           = "o-5.png";
$l_insignia[9]           = "o-6.png";
$l_insignia[10]          = "o-7.png";
$l_insignia[11]          = "o-8.png";
$l_insignia[12]          = "o-9.png";
$l_insignia[13]          = "o-10.png";
$l_insignia[14]          = "o-11.png";
$l_insignia[15]          = "o-12.png";
$l_insignia[16]          = "o-13.png";
$l_insignia[17]          = "o-14.png";
$l_insignia[18]          = "o-15.png";
$l_insignia[19]          = "o-16.png";

$l_insignia_name[0]           = "Spaceman Recruit";
$l_insignia_name[1]           = "Spaceman Apprentice";
$l_insignia_name[2]           = "Spaceman";
$l_insignia_name[3]           = "Petty Officer Third Class";
$l_insignia_name[4]           = "Petty Officer Second Class";
$l_insignia_name[5]           = "Petty Officer First Class";
$l_insignia_name[6]           = "Chief Petty Officer";
$l_insignia_name[7]           = "Senior Chief Petty Officer";
$l_insignia_name[8]           = "Master Chief Petty Officer";
$l_insignia_name[9]           = "Ensign";
$l_insignia_name[10]          = "Lieutenant Junior Grade";
$l_insignia_name[11]          = "Lieutenant";
$l_insignia_name[12]          = "Lieutenant Commander";
$l_insignia_name[13]          = "Commander";
$l_insignia_name[14]          = "Captain";
$l_insignia_name[15]          = "Rear Admiral (lower half)";
$l_insignia_name[16]          = "Rear Admiral (upper half)";
$l_insignia_name[17]          = "Vice Admiral";
$l_insignia_name[18]          = "Admiral";
$l_insignia_name[19]          = "Fleet Admiral";

$l_main_title            = "Главное меню";
$l_main_warpto           = "Прыжок в";
$l_main_autoroute        = "Autoroute to";
$l_main_rs_to            = "Лететь в";
$l_main_other            = "Прочия";
$l_main_shipyard1        = "верфь";
$l_main_shipyard2        = "Войти в ";
$l_traderoutes           = "Торговые пути";
$l_trade_control         = "Управление путями";
$l_youhave               = "У вас ";
$l_turns_used            = "Использовано ходов: ";
$l_turns_have            = "Осталось ходов: ";
$l_score                 = "Счёт: ";
$l_sector                = "Сектор";
$l_help                  = "Справка";
$l_faq                   = "ЧаВО";
$l_feedback              = "Связь";
$l_forums                = "Форум";
$l_logout                = "Отключиться";
$l_commands              = "Commands";
$l_command_no            = "Никого нет дома.";
$l_devices               = "Устройства";
$l_planets               = "Планеты";
$l_log                   = "Журнал";
$l_sector_def            = "Орбитальные силы";
$l_defense               = "Защита";
$l_read_msg              = "Читать почту";
$l_send_msg              = "Писать почту";
$l_rankings              = "Рейтинг";
$l_teams                 = "Альянсы";
$l_ohno                  = "Харакири";
$l_options               = "Параметры";
$l_navcomp               = "Навигатор";
$l_incompletemove        = "Предыдущий ход не завершён.";
$l_clicktocontinue       = "Жми сюда для продолжения";
$l_toplanetmenu          = "перейти в меню планеты.";
$l_nonexistant_pl        = "На несуществующей планете???";
$l_abord                 = ", на борту ";
$l_messages_wait         = " новых сообщений!";
$l_no_warplink           = "Некуда прыгать";
$l_scan                  = "сканировать";
$l_fullscan              = "Глубокое сканирование";
$l_port                  = "Порт";
$l_tradingport           = "Торговый порт";
$l_planet_in_sec         = "Планеты в секторе ";
$l_ships_in_sec          = "Другие корабли в секторе ";
$l_sector_0              = "Кораблёв-то, кораблёв! Не разберешь, хто есть где...";
$l_map                   = "Карта";
$l_autotrade				 = "Autotrades";
$l_onboard				 = "onboard a";
$l_classship = "class ship";
$l_traveled = "traveled to sector";
$l_max_planets = "Maximum habital planets";
$l_block_msg              = "Block Messages";
$l_probe = "Probes";
$l_sectorinfo               = "Sector Info";
$l_add_note="Add Note";
$l_view_note="View";
$l_notes="Notes";
$l_global_limitreached="You have reached the limit for the amount of time you are allowed to be online each day.  Log in again tomorrow after midnight.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Stored Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader's Lobby";

$l_common_prev="Previous Page";
$l_common_next="Next Page";
$l_common_totalpages="Total Pages";
$l_common_selectpage="Select Page: ";
$l_common_page="Page: ";
$l_templatechange = "Would you like to keep this Template?";

$l_im_fed_bounty = "The Federation has placed a bounty on you for attacking such a low ranked player.  The Federation will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_fed_bounty_title = "Federation placed a Bounty on you!";
$l_im_alliance_bounty = "The Alliance has placed a bounty on you for attacking such a low ranked player.  The Alliance will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_alliance_bounty_title = "Alliance placed a Bounty on you!";
$l_instant_messages_waiting = "You have [count] messages waiting for you.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Filled: ";
$l_hold_space_free = "Holds Empty: ";
$l_port_buys = "Port Buys: ";

?>
