<?php
$l_gns_title             = "Запуск торпеды мироздания";
$l_gns_turn              = "Вам нужен хотя бы один ход для запуска торпеды мироздания.";
$l_gns_onplanet          = "Вы не можете запустить торпеду мироздания, находясь на поверхностьи планеты.";
$l_gns_full              = "В этой звездной системе нет места для новой планеты.";
$l_gns_planetex          = "В этом секторе уже есть планета.";
$l_gns_nogenesis         = "У вас нет ни одной торпеды мироздания.";
$l_gns_forbid            = "Порождение новых планет в этом сектор запрещено.";
$l_gns_bforbid           = "Базы в этом секторе препятствуют созданию планеты.";
$l_gns_pcreate           = "Родилась новая планета!";
$l_sgns_title             = "Use Sector Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "You do not have any sector genesis devices.";
$l_sgns_forbid            = "Creating a sector genesis wormhole in this sector is not permitted.";
$l_sgns_forbid1            = "Creating a sector genesis wormhole a Federation Sector is not permitted.";
$l_sgcreate				= "Create New Sector Genesis Sector";
$l_sgcreatens				= "Create New Sector Genesis Link back to known space";
$l_sgns_forbid2            = "More than [limit] links in SG Sectors are not permitted.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "You do not have enough credits to create a new sector.";
$l_sgns_shipcredits            = "Credits on ship:";
$l_sgns_createcost            = "Cost to create new Sector:";
$l_sgns_complete            = "Normal Space Link Complete";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";
?>
