<?php
$l_warp_cantsame         = "Вы не можете связать сектор сам с собой.";
$l_warp_twoerror         = "Использование исказителя гиперпространства для создания двунаправленного гиперперехода к сектору [target_sector] запрещено.";
$l_warp_sectex           = "Невозможно создать гиперпереход из этого сектора - максимальное количество связей в секторе - $link_max .";
$l_warp_linked           = "Указанный сектор ([target_sector]) уже имеет гиперпереход в этот сектор.";
$l_warp_coneway          = "Создан односторонний гиперпереход к сектору";
$l_warp_ctwoway          = "Создан двусторонний гиперпереход к сектору";
$l_warp_nomoney          = "You do not have enough credits to create the warp link.";
$l_warp_noenergy          = "You do not have enough energy to create the warp link.";
?>
