<?php
// port.php port_purchase.php
$l_trade       = "Торговля";
$l_title_port       = "Торговля в порту";
$l_title_trade       = "Торгуемые товары";
$l_sector_war       = "Военное эмбарго";
$l_war_info       = "В этом секторе проводятся военные действия. Вы не можете прорваться в порт через вражеские силы.";
$l_no_trade       = "Торговля запрещена";
$l_no_trade_out       = "Торговля в этом порту для аутсайдеров запрещена";
$l_no_trade_info    = "Торговля в этом порту запрещена";
$l_buying       = "Покупка";
$l_selling       = "Продажа";
$l_commodity       = "Товар";
$l_amount       = "Количество";
$l_price       = "Цена";
$l_buy          = "Купить";
$l_sell          = "Продать";
$l_trade_st_info    = "В ваших трюмах [free_holds] единиц свободного места, батареи могут вместить ещё [free_power] единиц энергии, в кармане - [credits] кредов.";
$l_upgrade_port_title    = "Порт модернизации";
$l_device_port_title    = "Инструментальный порт";
$l_no_credits       = "Маловато кредов";
$l_creds_to_spend    = "Вы можете потратить [credits] кредов.";
$l_cost          = "Стоимость";
$l_avail       = "Доступность";
$l_profit       = "Доход";
$l_current       = "Текущий";
$l_current_level    = "Текущий уровень";
$l_current_qty       = "Текущий объём";
$l_max          = "Максимум";
$l_ifyouneedmore    = "Если нужны деньги, обратись в местное [igb] ";
$l_ifyouneedplan    = "Доступ в планетарное ";
$l_igb_term       = "отделение МГБ";
$l_upgrade       = "Модернизировать";
$l_unlimited       = "Безгранично";
$l_full          = "Полностью";
$l_equipped       = "Установлено";
$l_n_a          = "n/a";
$l_item          = "Предмет";
$l_totalcost       = "Стоимость";
$l_would_dump            = "Вы можете оставить всех ваших колонистов ";
$l_noport       = "Тута нема портов!";
$l_trade_turnneed    = "Для торговли нужен хотя бы один ход.";
$l_returnto_port1        = "здесь";
$l_returnto_port2        = " Жми [port_link] для возврата в портовое меню.";
$l_notenough_cargo    = "Куда пихаешь? Трюмы и без того полны.";
$l_notenough_power    = "И шо, таки ты думаешь, что аккумуляторы сделаны из резины?";
$l_notenough_credits    = "Ты наличность-то предъяви.";
$l_notenough_turns    = "Не хватает ходов.";
$l_trade_result       = "Подбиваем бабки";
$l_trade_complete    = "По рукам!";
$l_trade_upgraded     = "Моденизирован до уровня ";
$l_trade_added        = "добавлено";
$l_trade_installed     = "установлено";
$l_port_bounty        = "Согласно постановлению Правительства вы являетесь персоной нон-грата в этом порту.<BR>";
$l_port_bounty2     = "Нажмите <a href=\"port.php?pay=1\">здесь</a> для уплаты штрафа в размере [amount] кредов.";
$l_port_btynotenough     = "У вас недостаточно средств для уплаты штрафа в размере [amount] кредов.<BR>";
$l_port_bountypaid     = "Штраф уплачен. Нажмите <a href=\"port.php\">здесь</a> для продолжения.<BR>";
$l_port_loannotrade     = "Ваш счёт арестован МГБ за задержку выплаты кредита. Вы не сможете торговать в специализированных портах до возврата кредита.";
$l_port_returntospecial = "для возврата на склад.";
$l_ports_shiplimit = "Minimum Ship class to mount device: ";
$l_ports_needrepair = "Repair";
$l_spacedock_port_title	 = "Spacedock";

$l_ports_needcredits = "You do not have enough credits for this transaction.	The total cost is";
$l_ports_needcredits1 = "credits and you only have";

$l_ports_tradeforbidden = "Trade forbidden";
$l_ports_nooutsiders = "Trading at this port is not allowed for outsiders.";
$l_toprobemenu = "to go to the probe menu.";

$l_bought		 = "You bought";
$l_sold		 = "You sold";
$l_notenough_commodity	 = "You do not have enough [commodity] to complete the transaction.";
$l_exceed_commodity	 = "Number of [commodity] exceeds the supply/demand.  ";
$l_port_shiptoolarge = "Your ship is too large to trade at this port.";

$l_port_hold_unit= "Holds per Unit";

?>
