<?php
$l_ze_title              = "Редактировать настройки сектора";
$l_ze_notowner           = "Вы не владелец сектора, так что вы не можете управлять им.";
$l_ze_name               = "Имя сектора";
$l_ze_allow              = "Разрешено";
$l_ze_attacks            = "Разрешено атаковать корабли";
$l_ze_genesis            = "Разрешено создавать планеты";
$l_ze_return             = "чтобы вернутся на страницу информации о секторе";
$l_ze_saved              = "Изменения были сохранены.";
$l_ze_namematch = "ERROR: The Zone Name you provided is similar or matches an existing Zone Name.";
?>
