<?php
$l_feedback_title        ="Связь";
$l_feedback_to           ="Кому:";
$l_feedback_from         ="От:";
$l_feedback_topi         ="Тема:";
$l_feedback_feedback     ="Отчет об ошибке/недочете";
$l_feedback_message      ="Сообщение:";
$l_feedback_messent      ="Сообщение отправлено";
$l_feedback_subj         ="Встроенная система связи с администратором"; 
$l_feedback_info         ="Пожалуйста отправляйте сообщения на понятном языке!";
?>
