<?php
$l_warp_linkto           = "Гиперпереходы из этого сектора";
$l_warp_nolink           = "Нет гиперпереходов из этого сектора.";
$l_warp_query            = "К какому сектору вы хотите создать гиперпереход?";
$l_warp_oneway           = "В одном направлении?";
$l_warp_dest             = "Вы также можете уничтожить гиперпереход между секторами.";
$l_warp_destquery        = "К какому сектору вы хотите отрезать гиперпереход?";
$l_warp_bothway          = "В обоих направлениях";
$l_warp_create          = "Create a warp link between Sector: ";
$l_warp_andsector          = " and Sector: ";
$l_warp_distance          = " with a distance of ";
$l_warp_lightyears          = " lightyears";
$l_warp_delete          = "Delete warp link between Sector: ";
$l_warp_costcreate          = "Cost to create:";
$l_warp_costdelete          = "Cost to delete:";
$l_warp_costenergy          = "Energy needed: ";
$l_warp_twoerror         = "Использование исказителя гиперпространства для создания двунаправленного гиперперехода к сектору [target_sector] запрещено.";
?>
