<?php
$l_by_title              = "Награды";
$l_by_noturn             = "Необходим хотя бы один ход чтобы назначить или изменить награду.";
$l_by_amount             = "Награда за голову";
$l_by_place              = "Назначить награду";
$l_by_nobounties         = "Нет назначенных наград.";
$l_by_bountyon           = "Награда за голову";
$l_by_placedby           = "Назначена";
$l_by_thefeds            = "Федерацией";
$l_by_cancel             = "Отменить";
$l_by_yourself           = "Вы не можете назначить награду за себя.";
$l_by_notenough          = "У вас не хватает денег чтобы посместить такую награду.";
$l_by_toomuch            = "Вы не можете назначить такую награду. Максимальная назначаемая награда [percent] от вашего капитала";
$l_by_zeroamount         = "Награда должна быть более 0 кредитов.";
$l_by_placed             = "Награда назначена.";
$l_by_nobounty           = "Эта награда снята.";
$l_by_notyours           = "Эта награда назначена не вами.";
$l_by_canceled           = "Назначение награды отменено.";
$l_by_action             = "Действие";
$l_by_placebounty        = "Назначить или просмотреть награды.";
$l_by_moredetails        = "Кликните на имя чтобы получить информацию.";
$l_by_fedbounty          = "<font color='red' size='4'><b>Атака этого игрока вынудит федерацию поместить награду за вашу голову.</b></font>";
$l_by_fedbounty2         = "<font color='red' size='4'><b>федерация запрещает атаковать корабли намного меньше вашего. За вашу голову назначена награда.</b></font>";
$l_by_notexists          = "Игрок за которого вы назначаете награду не существует.";
$l_by_destroyed          = "Вы не можете назначить награду за голову игрока с уничтоженным кораблем.";
$l_by_nofedbounty		 = "You will not receive a bounty if you attack this players ship or planet.";
$l_by_fedcollectonly		 = "Only Federation can Collect Bounty";
$l_gotobounty          ="Click <A HREF=bounty.php>here</A> to return to the bounty menu.";

$l_by_fedbountyspy          = "<font color='red' size='4'><b>Placing a spy on this players planet would result in The Federation placing a bounty on you.</b></font>";
$l_by_fedbountyspy2         = "<font color='red' size='4'><b>The Federation does not approve of placing spies on much smaller players planets. It has placed a bounty on you.</b></font>";
$l_by_nofedbountyspy		 = "You will not receive a bounty if you place a spy on this players planet.";
$l_pay_partial = "Make Partial Payment";
$l_pay_button = "Pay";
$l_by_thealliance            = "The Alliance";
$l_by_alliancecollectonly		 = "Only the Alliance can Collect Bounty";
$l_by_bountyscan          = "Bounty";
?>
