<?php
$l_lrs_title             = "Глубокое сканирование космоса";
$l_lrs_nofull            = "Ваши радары не позволяют производить глубокое сканирование.";
$l_lrs_noturns           = "Необходимо иметь хотя бы $fullscan_cost ход для проведения глубокого сканирования.";
$l_lrs_used              = "Потрачен";
$l_lrs_turns             = "ход";
$l_lrs_left              = "осталось";
$l_lrs_reach             = "Из сектора [sector] можно попасть в следующие сектора:";
$l_lrs_links             = "Переходы";
$l_lrs_ships             = "Корабли";
$l_lrs_click             = "Нажмите на переход, чтобы попасть в соответствующий сектор.";
$l_lrs_cantscan          = "Не удается просканировать заданный сектор отсюда!";
$l_lrs_zero              = "В Нулевом секторе слишком много кораблей, чтобы их распознать!";
$l_lrs_moveto            = "для перехода в сектор";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Bounty</b></font>";
$l_log_titlet            = "Просмотр журнала";
$l_lrs_fedjammed           = "Federation is jamming all sensor scans.";
$l_lrs_imtitle             = "Sector Under Attack";
$l_lrs_imbody             = "is using a Sector Nova on";
$l_lrs_sectormissile_question             = " to fire sector missile.";
$l_log_months 		 = array('Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь');
$l_log_months_short 	 = array('Янв','Фев','Март','Апр','Май','Июнь','Июль','Авг','Сент','Окт','Ноя','Дек');
?>
