<?php
$l_opt_title             = "Параметры";
$l_opt_chpass            = "Смена пароля";
$l_opt_curpass           = "Текущий пароль:";
$l_opt_newpass           = "Новый пароль:";
$l_opt_newpagain         = "Еще разок:";
$l_opt_userint           = "Интерфейс";
$l_opt_usenew            = "Использовать новый расклад?";
$l_opt_lang              = "Язык";
$l_opt_template              = "Template";
$l_opt_select            = "Выберите:";
$l_opt_enabled           = "Включен";
$l_opt_save              = "Запомнить";
$l_opt_teamicon              = "Team Icon";
$l_opt_shipname              = "Shipname:";
$l_opt_mapwidth              = "Local and Galaxy Map Width:";
$l_opt_profiletitle = "Profile";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registered with Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "When you register your player on another server the template, shoutbox and news settings above will be used on the server.";
$l_opt_showshoutbox              = "Show Shoutbox:";
$l_opt_shownewscrawl              = "Show News Crawl:";
$l_opt_playername              = "Player Name:";
$l_opt_playernamecost              = "Federation Name Change Fee: [amount] credits";
?>
