<?php
$l_readm_title           = "Проверка почты";
$l_readm_delete          = "СООБЩЕНИЕ ПРИБИТО";
$l_readm_nomessage       = "Ваш почтовый ящик пуст...";
$l_readm_center          = "Главпочтамт";
$l_readm_sender          = "От кого";
$l_readm_captn           = "Капитан корабля";
$l_readm_del             = "Прибить";
$l_readm_repl            = "Ответить";
$l_readm_return            = "Click here to return to the main menu";
$l_readm_title2            = "Mail Reader";
$l_readm_delete            = "Delete All";
$l_readm_subject            = "Subject";
$l_readm_quote            = "Quote";
$l_readm_block            = "Block Sender";
$l_readm_alert            = "System Alert";
$l_readm_alertbody            = "Ship Computer";
?>
