<?php
$l_login_title			= "Имя:";
$l_login_pw			= "Пароль:";
$l_login_chooseres		= "Не удалось определить ваше разрешение экрана. Выберите наилучшее:";
$l_login_newp			= "Если вы новый игрок, нажмите <A HREF=\"new_player.php\">здесь</A>.";
$l_login_prbs			= "Проблемы?";   
$l_login_emailus		= "Пишите письма!";
$l_login_forgot_pw		= "Забыли пароль? Введите только имя и нажмите на вход.";
$l_login_settings 		= "Настройки игры";
$l_login_change			= "Сменить";
$l_login_title2			= "Main Login for AATraders";
$l_login_reset1			= "No Reset Scheduled";
$l_login_reset2			= "Scheduled Reset: ";
$l_login_reset3			= "Sched Reset: ";
$l_login_notice			= "Important Notice:";
$l_login_endadminnews			= "End of Admin News";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
