<?php
$l_opt2_title            = "Запомнить параметры";
$l_opt2_passunchanged    = "Пароль остался неизменным.<BR><BR>";
$l_opt2_srcpassfalse     = "Неверно введен текущий пароль. Пароль не изменён.<BR><BR>";
$l_opt2_newpassnomatch   = "Пароль подтвержден не верно. Пароль не изменён.<BR><BR>";
$l_opt2_passchanged      = "Пароль изменен.<BR><BR>";
$l_opt2_passchangeerr    = "Ошибка смены пароля<BR><BR>";
$l_opt2_userintup        = "Параметры интерфейса изменены.<BR><BR>";
$l_opt2_userintfail      = "Изменит параметры интерфейса не удалось.<BR><BR>";
$l_opt2_chlang           = "Язык изменен на [lang].<p>";
$l_opt2_chtemplate           = "Template has been set to [template].<p>";
$l_opt2_dhtmlup          = "Параметры DHTML изменены.<BR><BR>";
$l_opt2_dhtmlfail        = "Не удалось изменить параметры DHTML.<BR><BR>";
$l_opt2_shipnamechanged        = "Shipname changed to [name].<BR><BR>";
$l_opt2_playernamechanged        = "Player Name Changed to [name] and [amount] credits deducted from your ship account.<BR><BR>";
$l_opt2_mapwidth        = "Local and Galaxy Map Width: ";
?>
