<?php
$l_news_title            = "Новости Галактики";
$l_news_info             = "Галактическая сеть новостей - безусловный лидер<br>в сфере СМИ в этой галактике!<br>Мы делаем новости! Каждые 15 минут!<br>24 часа в сутки! 7 дней в неделю!<br>Наши спецы в главном офисе на <br>Цетаганде трудятся для вас!";
$l_news_for              = "Новости на";
$l_news_prev             = "что было вчерась";
$l_news_next             = "что будет завтра";
$l_news_none             = "Сегодня у новостей выходной.";
$l_news_flash            = "Заголовок";
$l_news_end              = "Конец новостям";
$l_news_bestviewed              = "Best viewed in Opera, Safari and IE";
$l_news_fedannouncements              = "Federation Announcements";
$l_news_planetarynews              = "Planetary News";
$l_news_planetshipnews              = "Planetary and Ship News";
$l_news_afteractionnews              = "After Action Combat News";


?>
