<?php
$l_pre_title             = "Изменить стандартные маршруты";
$l_pre_exceed            = "[preset] превышает максимум [sector_max]. Маршруты не запомнены.<BR><BR>";
$l_pre_set               = "Маршрут";
$l_pre_save              = "Запомнить";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
