<?php

// Confirmed common to multiple files:

$l_zname[1] 		 = "Espacio desconocido";
$l_zname[2] 		 = "Espacio de la Federación";
$l_zname[3] 		 = "Alliance space";
$l_zname[4] 		 = "Zona de Guerra";

$l_nova 		 = "Nova";
$l_nova 		 = "Nova Bomb";
$l_lssd 		 = "Dispositivo de Ultima Nave Avistada";
$l_lss 			 = "Ultima Nave";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Usar Editor de Enlace";
$l_warp_turn		 = "Necesitas al menos un turno para utilizar un Editor de Enlace.";
$l_warp_none		 = "No tienes ningún Editor de Enlace.";
$l_warp_forbid		 = "No está permitido usar un Editor de Enlace en este sector.";
$l_warp_nosector	 = "El sector no existe.";
$l_swarp_forbid		 = "Using a Warp Editor to or from SG sectors is not permitted.";
// Not yet confirmed common to multiple files:

$l_yes 			 = "Sí";
$l_no			 = "No";
$l_here			 = "aquí";
$l_submit		 = "Enviar";
$l_reset		 = "Borrar";
$l_all			 = "Todo";
$l_max			 = "Max";

$l_trade		 = "Trade";
$l_ore			 = "Minerales ";
$l_commodity		 = "Commodity";
$l_commodities		 = "Mercancías ";
$l_organics		 = "Alimentos ";
$l_goods		 = "Bienes ";
$l_energy		 = "Energía ";
$l_colonists		 = "Colonos ";
$l_credits 		 = "Créditos";
$l_units		 = "unidades de ";
$l_special		 = "Especial";
$l_upgrade_ports	 = "Mejoras";
$l_device_ports		 = "Dispositivos";
$l_spacedock		 = "Spacedock";
$l_casino		 = "Casino";
$l_spy = "Espías ";
$l_dig = "Dignitaries";

$l_cargo		 = "Cargamento ";
$l_fighters		 = "Cazas";
$l_mines		 = "Minas";
$l_torps		 = "Torpedos";

$l_none			 = "Ninguno";
$l_unnamed		 = "Sin Nombre";
$l_name			 = "Nombre";
$l_unowned		 = "Sin dueño";
$l_unknown		 = "Desconocido";
$l_clickme 		 = "Haz clic aquí";
$l_player  		 = "Jugador";
$l_ship			 = "Nave ";
$l_ships		 = "Naves ";
$l_set			 = "Ajustar";
$l_realspace		 = "Hiperespacio";
$l_armorpts		 = "puntos de blindaje";
$l_links		 = "Enlaces";
$l_login_email          = "Dirección de correo electrónico:";
$l_add			 = "Add";
$l_teamforum			 = "Team Forum";
$l_teamships			 = "Team Ships";
$l_tutorial			 = "Tutorial/Help";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Team Icon";
$l_debris			 = "Debris";
$l_localmap			 = "Local Map";
$l_arm_weap              = "Armor & Weapons";
$l_3dmap			 = "3D Galaxy Map";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Space Probes";
$l_warpeditors = "Warp Editors";
$l_genesistorps = "Genesis Torpedoes";
$l_sgtorps = "SG Torpedos";
$l_minesfighters = "Mines/Fighters";
$l_ewarp = "Emergency Warp";
$l_reports = "Reports";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sector Notes";
$l_maps = "Maps";
$l_messages = "Messages";
$l_shiptype = "Ship Type";
$l_help = "Help";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team defenses";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet defenses";
$l_changeproduction = "Change Production";
$l_galacticarm = "Galactic Arm";
$l_armor		 = "Armor";
$l_news_none             = "Hoy no hay noticias.";

$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_neutral       = "Neutral";

$l_global_mmenu          ="Haz clic <A HREF=main.php>aquí</A> para volver al menú principal.";
$l_global_mlogin         ="Haz clic <A HREF=index.php>aquí</A> para volver a la pantalla de conexión.";
$l_global_needlogin      ="Debes conectarte, haz clic <A HREF=index.php>aquí</A>.";
$l_global_died           ="¡Jugador MUERTO! <a href=log.php>Aquí</a> está lo que ocurrió<BR><BR>¡Que tengas mejor suerte la próxima vez!";
$l_global_warzone        ="¡La zona es ahora Zona de Guerra!";
$l_global_nzone          ="La zona es una zona neutral.";
$l_global_team           ="La zona pertenece ahora al equipo";
$l_global_player         ="La zona pertenece ahora al jugador";
$l_global_nochange       ="El dominio sobre la zona no ha cambiado";
$l_insignia[0]           = "1c.png";
$l_insignia[1]           = "2c.png";
$l_insignia[2]           = "3c.png";
$l_insignia[3]           = "4c.png";
$l_insignia[4]           = "o-1.png";
$l_insignia[5]           = "o-2.png";
$l_insignia[6]           = "o-3.png";
$l_insignia[7]           = "o-4.png";
$l_insignia[8]           = "o-5.png";
$l_insignia[9]           = "o-6.png";
$l_insignia[10]          = "o-7.png";
$l_insignia[11]          = "o-8.png";
$l_insignia[12]          = "o-9.png";
$l_insignia[13]          = "o-10.png";
$l_insignia[14]          = "o-11.png";
$l_insignia[15]          = "o-12.png";
$l_insignia[16]          = "o-13.png";
$l_insignia[17]          = "o-14.png";
$l_insignia[18]          = "o-15.png";
$l_insignia[19]          = "o-16.png";

$l_insignia_name[0]           = "Spaceman Recruit";
$l_insignia_name[1]           = "Spaceman Apprentice";
$l_insignia_name[2]           = "Spaceman";
$l_insignia_name[3]           = "Petty Officer Third Class";
$l_insignia_name[4]           = "Petty Officer Second Class";
$l_insignia_name[5]           = "Petty Officer First Class";
$l_insignia_name[6]           = "Chief Petty Officer";
$l_insignia_name[7]           = "Senior Chief Petty Officer";
$l_insignia_name[8]           = "Master Chief Petty Officer";
$l_insignia_name[9]           = "Ensign";
$l_insignia_name[10]          = "Lieutenant Junior Grade";
$l_insignia_name[11]          = "Lieutenant";
$l_insignia_name[12]          = "Lieutenant Commander";
$l_insignia_name[13]          = "Commander";
$l_insignia_name[14]          = "Captain";
$l_insignia_name[15]          = "Rear Admiral (lower half)";
$l_insignia_name[16]          = "Rear Admiral (upper half)";
$l_insignia_name[17]          = "Vice Admiral";
$l_insignia_name[18]          = "Admiral";
$l_insignia_name[19]          = "Fleet Admiral";

$l_main_title            = "Menú Principal";
$l_main_warpto           = "Enlace a";
$l_main_autoroute        = "Autoroute to";
$l_main_rs_to            = "Salto a";
$l_main_other            = "Otro";
$l_main_shipyard1        = "Astillero";
$l_main_shipyard2        = "Accede al ";
$l_traderoutes           = "Rutas Comerciales";
$l_trade_control         = "Centro del Comercio";
$l_youhave               = "Tienes ";
$l_turns_used            = "Turnos usados: ";
$l_turns_have            = "Turnos disponibles: ";
$l_score                 = "Puntuación: ";
$l_sector                = "Sector";
$l_help                  = "Ayuda";
$l_faq                   = "FAQ";
$l_feedback              = "Contáctanos";
$l_forums                = "Forums";
$l_logout                = "Desconectar";
$l_commands              = "Acciones";
$l_command_no            = "Acción no disponible.";
$l_devices               = "Dispositivos";
$l_planets               = "Planetas ";
$l_log                   = "Registro";
$l_sector_def            = "Defensas Sector";
$l_defense               = "Defensas";
$l_read_msg              = "Leer Mensajes";
$l_send_msg              = "Enviar Mensajes";
$l_rankings              = "Clasificación";
$l_teams                 = "Equipos";
$l_ohno                  = "Auto-Destruir";
$l_options               = "Opciones";
$l_navcomp               = "Computadora Nav.";
$l_incompletemove        = "No has completado el movimiento anterior.";
$l_clicktocontinue       = "Haz clic aquí para continuar";
$l_toplanetmenu          = "para ir al menú de planetas.";
$l_nonexistant_pl        = "En un planeta no existente???";
$l_abord                 = ", a bordo de ";
$l_messages_wait         = " Mensajes no leídos.";
$l_no_warplink           = "No hay enlaces";
$l_scan                  = "Escanear";
$l_fullscan              = "Scan Completo";
$l_port                  = "Puerto";
$l_tradingport           = "Puerto comercial";
$l_planet_in_sec         = "Planetas en el sector ";
$l_ships_in_sec          = "Otras naves en el sector ";
$l_sector_0              = "¡Hay tanto tráfico en el Sol que no puedes rastrear ninguna nave!";
$l_map                   = "Mapa";
$l_autotrade				 = "Autotrades";
$l_onboard				 = "onboard a";
$l_classship = "class ship";
$l_traveled = "traveled to sector";
$l_max_planets = "Maximum habital planets";
$l_block_msg              = "Block Messages";
$l_probe = "Probes";
$l_sectorinfo               = "Sector Info";
$l_add_note="Add Note";
$l_view_note="View";
$l_notes="Notes";
$l_global_limitreached="You have reached the limit for the amount of time you are allowed to be online each day.  Log in again tomorrow after midnight.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Stored Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader's Lobby";

$l_common_prev="Previous Page";
$l_common_next="Next Page";
$l_common_totalpages="Total Pages";
$l_common_selectpage="Select Page: ";
$l_common_page="Page: ";
$l_templatechange = "Would you like to keep this Template?";

$l_im_fed_bounty = "The Federation has placed a bounty on you for attacking such a low ranked player.  The Federation will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_fed_bounty_title = "Federation placed a Bounty on you!";
$l_im_alliance_bounty = "The Alliance has placed a bounty on you for attacking such a low ranked player.  The Alliance will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_alliance_bounty_title = "Alliance placed a Bounty on you!";
$l_instant_messages_waiting = "You have [count] messages waiting for you.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Filled: ";
$l_hold_space_free = "Holds Empty: ";
$l_port_buys = "Port Buys: ";

?>
