<?php
$l_defense_deploy_title           ="Desplegar Defensas de Sector";
$l_defense_deploy_noturn          ="Necesitas al menos un turno para desplegar defensas de sector.";
$l_defense_deploy_nopermit        ="No está permitido desplegar Minas y Cazas en este sector.";
$l_defense_deploy_nodeploy        ="No puedes desplegar defensas aquí. Otra nave o Equipo tiene minas o cazas desplegados en el sector.";
$l_defense_deploy_info1           ="Actualmente estás en el sector [sector]. Hay [mines] minas y [fighters] cazas aquí.";
$l_defense_deploy_info2           ="Tienes [mines] minas y [fighters] cazas disponibles para desplegar";
$l_defense_deploy_deploy          ="Desplegar";
$l_defense_deploy_deployed        ="Desplegado";
$l_defense_deploy_att             ="Atacar";
$l_defense_deploy_notorps         ="No tienes suficientes torpedos.";
$l_defense_deploy_nofighters      ="No tienes suficientes cazas.";
$l_defense_deploy_dmines          ="Desplegadas [mines] minas.";
$l_defense_deploy_dfighter        ="Deployed [fighters] fighters.";
$l_defense_deploy_max_fighters    ="This sector can support a maximum of [amount] fighters.";
$l_defense_deploy_toomanyfighters ="You have tried to deploy more fighters than the sector can support.";
?>
