<?php
$l_login_title			= "Conectar";
$l_login_pw			= "Contraseña:";
$l_login_chooseres		= "Imposible detectar tu resolución de pantalla. Por favor elige la que mejor se ajuste:";
$l_login_newp			= "Si eres nuevo, haz clic <A HREF=\"new_player.php\">aquí</A>.";
$l_login_prbs			= "Problemas?";   
$l_login_emailus		= "Envíanos un email";
$l_login_forgot_pw		= "Olvidaste tu contraseña?  Deja el campo vacío y pulsa Conectar.";
$l_login_settings 		= "Ajustes del Juego";
$l_login_change			= "Cambiar";
$l_login_title2			= "Main Login for AATraders";
$l_login_reset1			= "No Reset Scheduled";
$l_login_reset2			= "Scheduled Reset: ";
$l_login_reset3			= "Sched Reset: ";
$l_login_notice			= "Important Notice:";
$l_login_endadminnews			= "End of Admin News";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
