<?php
$l_nav_title             = "Computadora de Navegación";
$l_nav_nocomp            = "No está disponible la Computadora de Navegación";
$l_nav_query             = "Introduce el sector hacia el que encontrar una ruta: ";
$l_nav_pathfnd           = "Ruta encontrada";
$l_nav_answ1             = "Te llevará";
$l_nav_answ2             = "turnos llegar al sector.";
$l_nav_proper            = "You need to upgrade your Fighter Bay technology before your fighters can find a warp route for that distance.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
