<?php
$l_att_title             = "Atacar Nave";
$l_att_notarg            = "El objetivo no se encuentra en este sector.";
$l_att_noturn            = "Necesitas al menos un turno para atacar.";
$l_att_noatt             = "No está permitido atacar naves en este sector.";
$l_att_flee              = "¡El objetivo consiguió evitarte!";
$l_att_ewd               = "¡El objetivo utilizó un dispositivo de salto de emergencia al ser atacado!";
$l_att_att               = "Atacando ";
$l_att_beams             = "Beam Exchange";
$l_att_torps             = "Torpedo Exchange";
$l_att_fighters          = "Fighter Exchange";
$l_att_lost              = " perdidos";
$l_att_ylost             = "Perdiste ";
$l_att_sdown             = ": ¡Sus escudos no funcionan!";
$l_att_ydown             = "¡Tus escudos no funcionan!";
$l_att_shits             = "Los escudos de [name] han sido alcanzados en ";
$l_att_yhits             = "Tus escudos son alcanzados en ";
$l_att_dmg               = " de daño";
$l_att_sarm              = "¡El blindaje de [name] ha sido destruido!";
$l_att_yarm              = "¡Tu blindaje ha sido alcanzado!";
$l_att_ashit             = "El blindaje de [name] ha sido alcanzado en ";
$l_att_ayhit             = "Tu blindaje ha sido alcanzado en ";

$l_att_efhit             = "'s fighters are destroyed.";
$l_att_yfhit             = "of your fighters are destroyed.";
$l_att_ethit             = "'s torpedoes are destroyed.";
$l_att_ythit             = "of your torpedoes are destroyed.";
$l_att_of             = "of";
$l_att_lostt             = "lost all torpedoes.";
$l_att_ylostt            = "You lost all torpedoes.";

$l_att_lostf             = " perdió todos los cazas.";
$l_att_ylostf            = "Perdiste todos los cazas.";
$l_att_sdest             = "La nave de [name] ha sido destruida.";
$l_att_espod             = "¡Fue lanzada una cápsula de escape!";
$l_att_ysalv             = "Salvaste [ship_salvage_rate]% de la nave, valorado en [ship_salvage] créditos.<BR> Tu puntuación ha aumentado en [rating_change] puntos.";
$l_att_andused           = " y usó ";
$l_att_stilship          = "No destruiste la nave de [name]";
$l_att_atyou             = " te atacó";
$l_att_and               = " y ";
$l_att_yshiplost         = "¡Tu nave ha sido destruida!";
$l_att_salv              = "[name] salvó [ship_salvage_rate]% de la nave, valorado en [ship_salvage] créditos";
$l_att_loosepod		 	 = "¡Afortunadamente tienes una cápsula de escape!";

$l_att_tnobeams		 = " seams to be out of beam energy.";
$l_att_tnobeamsf		 = " seams to be out of beam energy and cannot attack your fighters.";
$l_att_tnobeamst		 = " seams to be out of beam energy and cannot attack your torpedoes.";
$l_att_tfnoattack		 = " isn't sending any fighters to attack your ship.";
$l_att_tnotorps		 = " seems to be out of torpedoes.";

$l_att_anobeams		 = "You have exhausted your ships beam energy.";
$l_att_anobeamsf		 = "You have exhausted your ships beam energy and cannot attack the enemy fighters.";
$l_att_anobeamst		 = "You have exhausted your ships beam energy and cannot attack the enemy torpedoes.";
$l_att_anofighters		 = "Your ship has exhausted all availible fighters.";
$l_att_anotorps		 = "You have exhausted your availible torpedoes.";
$l_att_imtitle		 = "Ship Under Attack";
$l_att_imbody		 = "is attacking your ship.";

$l_att_luckybeams		 = "Enemy beams overload inflicting";
$l_att_luckyfighters	 = "Enemy fighters make a surprise lightening attack and cause";
$l_att_luckytorps		 = "Enemy torpedoes induce a cascading damage effect causing";
$l_att_luckytimes		 = "times the normal damage!";
?>
