<?php
$l_sf_attacking          = "Los cazas de la defensa del sector te están atacando!<BR>";
$l_sf_destfight          = "Tus láseres destruyeron [lost] cazas<BR>";
$l_sf_destfightb         = "Tus láseres destruyeron [lost] cazas<BR>";
$l_sf_torphit            = "Torpedos golpearon objetivo:";
$l_sf_destfightt         = "Tus torpedos destruyeron [lost] cazas<BR>";
$l_sf_fighthit           = "Ataque de Cazas:";
$l_sf_destfightall       = "Destruiste todo los cazas.<BR>";
$l_sf_destfightt2        = "Destruiste [lost] cazas.<BR>";
$l_sf_lostfight          = "Perdiste todos los cazas.<BR>";
$l_sf_lostfight2         = "Perdiste [lost] cazas.<BR>";
$l_sf_armorbreach        = "Tu blindaje ha sido destruido!<BR>";
$l_sf_armorbreach2       = "Tu blindaje ha sido dañado en [lost] puntos.<BR>";
$l_sf_sendlog            = "[player] destruyó [lost] cazas de defensa de sector en el sector [sector].";
$l_sf_lreport            = "Perdiste [armor] puntos de blindaje, [fighters] cazas, y usaste [torps] torpedos.<BR><BR>";
$l_sf_shipdestroyed      = "Tu nave ha sido destruida!<BR><BR>";
$l_sf_sendlog2           = "Cazas de la defensa de sector destruyeron a [player] en el sector [sector].";
$l_sf_escape             = "Afortunadamente tienes una cápsula de escape!<BR><BR>";

$l_sf_fnoattack		 = " isn't sending any fighters to attack your fighters.";
$l_sf_fnoattackt	 = " isn't sending any fighters to attack your torpedoes.";
$l_sf_fnoattacka	 = " isn't sending any fighters to attack your armor.";
$l_sf_flaunchmalf1		 = "Your fighter launching system has malfunctioned.";
$l_sf_flaunchmalf2		 = "You have only been able to launch ";
$l_sf_flaunchmalf3		 = " percent of your fighters.";
$l_sf_fightertorpexg		 = "Fighter to Torpedo/Mine Exchange";
$l_sf_torpfighterexg		 = "Ship Torpedo to Sector Fighter Exchange";
$l_sf_fighterarmorexg		 = "Sector Fighter to Ship Armor Exchange";
$l_sf_tlaunchmalf1		 = "Your torpedo launching system has malfunctioned.";
$l_sf_tlaunchmalf2		 = "You have only been able to launch ";
$l_sf_tlaunchmalf3		 = " percent of your torpedoes.";
$l_sf_bountysd		 = "You have attacked a sector containing a planet that would give you a bounty if you attacked the planet.  The Federation has activated an automatic self-destruct on all of your fighters and torpedoes. Do not attack the sector defenses in this sector again.  You have been warned!";
?>
