<?php
$l_sendm_title           = "Enviar Mensaje";
$l_sendm_to              = "A";
$l_sendm_from            = "Desde";
$l_sendm_ally            = "Equipo:";
$l_sendm_subj            = "Asunto";
$l_sendm_mess            = "Mensaje";
$l_sendm_send            = "Enviar";
$l_sendm_sent            = "Mensaje enviado";
$l_sendm_blocked            = " has blocked you from sending messages.";
$l_sendm_blockmanager            = "Message Block Manager";
?>
