<?php
$l_readm_title           = "Leer Mensaje";
$l_readm_delete          = "MENSAJE BORRADO";
$l_readm_nomessage       = "No tienes nuevos mensajes...";
$l_readm_center          = "Centro de Recogida de Mensajes";
$l_readm_sender          = "Remitente";
$l_readm_captn           = "Capitán del";
$l_readm_del             = "Borrar";
$l_readm_repl            = "Responder";
$l_readm_return            = "Click here to return to the main menu";
$l_readm_title2            = "Mail Reader";
$l_readm_delete            = "Delete All";
$l_readm_subject            = "Subject";
$l_readm_quote            = "Quote";
$l_readm_block            = "Block Sender";
$l_readm_alert            = "System Alert";
$l_readm_alertbody            = "Ship Computer";
?>
