<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] chocó con  [chm_roll] minas en el sector [chm_sector].";         
$l_chm_youlostminedeflectors    = "Perdiste [chm_roll] deflectores de minas.";
$l_chm_youlostallminedeflectors = "Perdiste todos tus deflectores de minas.";
$l_chm_youhadnominedeflectors  = "No tienes deflectores de minas.";
$l_chm_yourshieldshitforminesdmg        = "Tus escudos han sido alcanzados en [chm_mines_left] puntos.";
$l_chm_yourshieldsaredown       = "¡Tus escudos están desactivados!";
$l_chm_youlostallyourshields    = "¡Perdiste todos tus escudos!";
$l_chm_yourarmorhitforminesdmg  = "Tu blindaje ha sido alcanzado en [chm_mines_left] puntos.";
$l_chm_yourhullisbreached       = "¡Se ha abierto brecha en tu casco!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] fue destruido por tus minas en el sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "¡Tu nave ha sido destruida!";
$l_chm_luckescapepod     = "¡Afortunadamente tienes una cápsula de escape!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
