<?php
// port.php port_purchase.php
$l_trade		 = "Comercio";
$l_title_port		 = "Comercio en Puerto";
$l_title_trade		 = "Comercio de Mercancías";
$l_sector_war		 = "Embargo de guerra";
$l_war_info		 = "Guerra total en el sector. No puedes alcanzar el puerto atravesando las fuerzas hostiles.";
$l_no_trade		 = "Comercio prohibido";
$l_no_trade_out		 = "No está permitido comerciar en este puerto a intrusos";
$l_no_trade_info	 = "No está permitido comerciar en este puerto";
$l_buying		 = "Compra";
$l_selling		 = "Venta";
$l_commodity		 = "Mercancía ";
$l_amount		 = "Cantidad ";
$l_price		 = "Precio ";
$l_buy			 = "Comprar";
$l_sell			 = "Vender ";
$l_trade_st_info	 = "Tienes [free_holds] de espacio de carga vacío, puedes transportar [free_power] unidades más de energía, y tienes [credits] créditos.";
$l_upgrade_port_title	 = "Puerto de Actualización";
$l_device_port_title	 = "Puerto de Dispositivos";
$l_no_credits		 = "No tienes suficientes créditos";
$l_creds_to_spend	 = "Tienes [credits] créditos para gastar.";
$l_cost			 = "Coste ";
$l_avail		 = "Disponible ";
$l_profit		 = "Beneficio ";
$l_current		 = "Actual ";
$l_current_level	 = "Nivel actual";
$l_current_qty		 = "Cantidades actuales";
$l_max			 = "Max ";
$l_ifyouneedmore	 = "Si necesitas más puedes acceder al [igb] de este puerto ";
$l_ifyouneedplan	 = "Acceder a";
$l_igb_term		 = "Terminal Bancaria de IGB";
$l_upgrade		 = "Actualizar";
$l_unlimited		 = "Ilimitado";
$l_full			 = "Completo";
$l_equipped		 = "Equipado";
$l_n_a			 = "n/d";
$l_item			 = "Item ";
$l_totalcost		 = "Coste total";
$l_would_dump	         = "Si quieres descargar todos los colonos, haz clic ";
$l_noport		 = "¡No hay puerto aquí!";
$l_trade_turnneed	 = "Necesitas al menos un turno para comerciar con el puerto o planeta.";
$l_returnto_port1        = " aquí";
$l_returnto_port2        = " Haz clic en [port_link] para volver al menú de puerto.";
$l_notenough_cargo	 = "No tienes suficiente espacio de carga libre para las mercancías que deseas comprar.";
$l_notenough_power	 = "No tienes suficientes baterías para almacenar la energía que deseas comprar.";
$l_notenough_credits	 = "No tienes suficientes créditos para completar la transacción.";
$l_notenough_turns	 = "No tienes suficientes turnos para completar la transacción.";
$l_trade_result		 = "Resultado de la transacción";
$l_trade_complete	 = "Transacción completada";
$l_trade_upgraded 	 = "Actualizado a nivel ";
$l_trade_added 		 = " añadidos";
$l_trade_installed 	 = " instalado";
$l_port_bounty 		 = "No puedes acceder a un puerto especial mientras tengas recompensa fijada sobre ti por parte de la Federación.<BR>";
$l_port_bounty2 	 = "Haz clic <a href=\"port.php?pay=1\">aquí</a> para pagar la recompensa de [amount] créditos.";
$l_port_btynotenough 	 = "No tienes créditos suficientes para pagar la recompensa de [amount] créditos.<BR>";
$l_port_bountypaid 	 = "Has pagado la recompensa. Haz clic <a href=\"port.php\">aquí</a> para continuar.<BR>";
$l_port_loannotrade 	 = "El IGB a emitido una orden de cierre sobre tu cuenta en la nave debido a la demora en el pago del préstamo. No puedes comerciar en los puertos especiales hasta devolver el préstamo.";
$l_port_returntospecial = " para volver al almacén de suministros.";
$l_ports_shiplimit = "Minimum Ship class to mount device: ";
$l_ports_needrepair = "Repair";
$l_spacedock_port_title	 = "Spacedock";

$l_ports_needcredits = "You do not have enough credits for this transaction.	The total cost is";
$l_ports_needcredits1 = "credits and you only have";

$l_ports_tradeforbidden = "Trade forbidden";
$l_ports_nooutsiders = "Trading at this port is not allowed for outsiders.";
$l_toprobemenu = "to go to the probe menu.";

$l_bought		 = "You bought";
$l_sold		 = "You sold";
$l_notenough_commodity	 = "You do not have enough [commodity] to complete the transaction.";
$l_exceed_commodity	 = "Number of [commodity] exceeds the supply/demand.  ";
$l_port_shiptoolarge = "Your ship is too large to trade at this port.";

$l_port_hold_unit= "Holds per Unit";

?>