<?php
$l_ze_title              = "Editar Zona";
$l_ze_notowner           = "No eres el propietario de esta zona así que no puedes editarla.";
$l_ze_name               = "Nombre de la zona";
$l_ze_allow              = "Permitir";
$l_ze_attacks            = "Permitir atacar naves";
$l_ze_genesis            = "Permitir crear nuevos planetas";
$l_ze_return             = "para volver a la página de información de zona";
$l_ze_saved              = "Los cambios han sido guardados.";
$l_ze_namematch = "ERROR: The Zone Name you provided is similar or matches an existing Zone Name.";
?>
