<?php
$l_opt2_title            = "Guardando Opciones";
$l_opt2_passunchanged    = "No se modificó la contraseña.<BR><BR>";
$l_opt2_srcpassfalse     = "Contraseña anterior incorrecta. La contraseña no fue modificada.<BR><BR>";
$l_opt2_newpassnomatch   = "los campos de la nueva contraseña no concuerdan. La contraseña no fue modificada.<BR><BR>";
$l_opt2_passchanged      = "Contraseña modificada.<BR><BR>";
$l_opt2_passchangeerr    = "Error modificando la contraseña.<BR><BR>";
$l_opt2_userintup        = "Actualizado el ajuste del interfaz de usuario.<BR><BR>";
$l_opt2_userintfail      = "El ajuste de la interfaz del usuario no pudo ser actualizado.<BR><BR>";
$l_opt2_chlang           = "El idioma ha sido cambiado a [lang].<p>";
$l_opt2_chtemplate           = "Template has been set to [template].<p>";
$l_opt2_dhtmlup          = "Actualizado el ajuste de página Html dinámica.<BR><BR>";
$l_opt2_dhtmlfail        = "El ajuste de página Html dinámica no pudo ser actualizado.<BR><BR>";
$l_opt2_shipnamechanged        = "Shipname changed to [name].<BR><BR>";
$l_opt2_playernamechanged        = "Player Name Changed to [name] and [amount] credits deducted from your ship account.<BR><BR>";
$l_opt2_mapwidth        = "Local and Galaxy Map Width: ";
?>
