<?php
$l_opt_title             = "Opciones";
$l_opt_chpass            = "Cambiar contraseña";
$l_opt_curpass           = "Contraseña actual:";
$l_opt_newpass           = "Nueva contraseña:";
$l_opt_newpagain         = "Nueva contraseña (de nuevo):";
$l_opt_userint           = "Interfaz del usuario";
$l_opt_usenew            = "Usar nuevo esquema de interfaz?";
$l_opt_lang              = "Idioma";
$l_opt_template              = "Template";
$l_opt_select            = "Selecciona uno:";
$l_opt_enabled           = "Habilitado";
$l_opt_save              = "Guardar";
$l_opt_teamicon              = "Team Icon";
$l_opt_shipname              = "Shipname:";
$l_opt_mapwidth              = "Local and Galaxy Map Width:";
$l_opt_profiletitle = "Profile";
$l_opt_profile = "If you have a Player Profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> and would like to register this game with that profile click ";
$l_opt_profilereg = "Registered with Profile Server";
$l_opt_profilerereg = "Re-register Player Profile for this game at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate = "Save this games template, shoutbox and news settings in your profile at <a href='http://www.aatraders.com'>www.aatraders.com</a> click ";
$l_opt_profileupdate2 = "When you register your player on another server the template, shoutbox and news settings above will be used on the server.";
$l_opt_showshoutbox              = "Show Shoutbox:";
$l_opt_shownewscrawl              = "Show News Crawl:";
$l_opt_playername              = "Player Name:";
$l_opt_playernamecost              = "Federation Name Change Fee: [amount] credits";
?>
