<?php
$l_chf_youretreatback    = "Retrocedes a tu posición anterior.";
$l_chf_movefailed        = "Movimiento fallido.";
$l_chf_thefightersdetectyou     = "¡Los cazas te detectaron!";
$l_chf_therearetotalfightersindest      = "Hay [chf_total_sector_fighters] cazas en el sector de destino.";
$l_chf_youcanretreat     = "<B>Retroceder</B> - Te costará un turno extra.";
$l_chf_inputfight        = "<B>Luchar</B> - Debes derrotar a todos los cazas para entrar en el sector.";
$l_chf_inputcloak        = "<B>Despistar</B> - Usa tu dispositivo de camuflaje e intenta evitar a los cazas.";
$l_chf_go                = "Adelante";
$l_chf_inputrun        = "<B>Attack and Run</B> - You do a lightening attack run and retreat.  But you MAY take some damage during retreat.";
?>
