<?php
$l_login_sclosed		= "Servidor Cerrado";       
$l_login_closed_message		= "Servidor cerrado hasta más noticia.";                
$l_login_title2			= "Fase Dos de la Conexión";
$l_login_banned			= "<b>Has sido vetado de este juego por el administrador del juego. No eres bienvenido en este servidor. La próxima vez, compórtate bien.</b>";
$l_login_died			= "Tu nave fue destruida, pero tu cápsula de escape os salvó a tí y tu gente.  Haz clic <A HREF=main.php>aquí</A> para continuar con una nueva nave.";
$l_login_newbie			= "Debido a la gravedad de este suceso y al virulento ataque en tu contra, la Federación ha decidido de forma clemente clonarte a partir de tus restos.  Pero, incluso hoy en día los nuevos clones no poseen nada, excepto lo indispensable para comenzar de nuevo.  Se te proporcionará una nave básica y unos pocos créditos para volver a empezar.  Sé más próspero en esta nueva vida.";
$l_login_newlife		= "Haz clic <A HREF=main.php>aquí</A> para continuar en una nueva vida.";
$l_login_looser			= "No tienes cápsula de escape, y debido a tu poco éxito en esta vida, la Federación rehusa a clonarte.  Tus restos deberían con el tiempo entrar en algún campo gravitatorio, con la esperanza de ser usados para crear vida en algún lugar... dentro de varios miles de millones de años.<BR><BR> Que tengas más suerte la próxima vez...";
$l_login_4gotpw1		= "La contraseña introducida no es correcta.<BR><BR>  Si olvidaste la contraseña, ";
$l_login_4gotpw2		= "para que te sea enviada.<BR><BR>  Si no,";     
$l_login_4gotpw3		= "para intentarlo de nuevo.  Intento registrado con la dirección IP ";
$l_login_noone			= "¡No existe tal jugador! - Crea un nuevo jugador <A HREF=new_player.php>aquí</A>.";
$l_login_diedincident			= "You have died in a horrible incident.";
$l_login_blackbox			= " is the blackbox information that was retrieved from your ships wreckage.";
$l_new_login             = "to go to the login screen.";
$l_login_playerlimit		= "The server has reached the maximum number of players it supports.  Please try logging in at a later time.";                
?>
