<?php
$l_news_title            = "Noticias del Universo";
$l_news_info             = "¡FNN se extiende por todos los confines de la galaxia <br>para distribuir las noticias e información.<br>Funciona las 24 horas, 7 días a la semana, gracias <br>al personal de la sede de la galaxia de FNN <br>en Alfa Centauri y de las sucursales repartidas por la galaxia!";
$l_news_for              = "Las noticias del ";
$l_news_prev             = "jornada anterior ";
$l_news_next             = " siguiente jornada";
$l_news_none             = "Hoy no hay noticias.";
$l_news_flash            = "Avance informativo";
$l_news_end        		 = "Fin de las noticias";
$l_news_bestviewed              = "Best viewed in Opera, Safari and IE";
$l_news_fedannouncements              = "Federation Announcements";
$l_news_planetarynews              = "Planetary News";
$l_news_planetshipnews              = "Planetary and Ship News";
$l_news_afteractionnews              = "After Action Combat News";


?>
