<?php
$l_pre_title             = "Cambiar Saltos Prefijados";
$l_pre_exceed            = "El Salto Prefijado [preset] supera el el máximo de la Galaxia de [sector_max] sectores. No se guardó ningún Prefijado.<BR><BR>";
$l_pre_set               = "Salto Prefijado";
$l_pre_save              = "Guardar";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
