<?php
$l_gns_title             = "Usar Dispositivo Génesis";
$l_gns_turn              = "Necesitas al menos un turno para usar el dispositivo Génesis.";
$l_gns_onplanet          = "No puedes usar este dispositivo mientras estés en la superficie del planeta.";
$l_gns_full              = "Este sistema solar ya está lleno.";
$l_gns_planetex          = "Ya hay un planeta en este sector.";
$l_gns_nogenesis         = "No dispones de dispositivos Génesis.";
$l_gns_forbid            = "Crear un planeta en este sector no está permitido.";
$l_gns_bforbid           = "Las bases en este sector interfieren con tu dispositivo Génesis. No es posible la creación de planetas.";
$l_gns_pcreate           = "Planeta creado.";
$l_sgns_title             = "Use Sector Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "You do not have any sector genesis devices.";
$l_sgns_forbid            = "Creating a sector genesis wormhole in this sector is not permitted.";
$l_sgns_forbid1            = "Creating a sector genesis wormhole a Federation Sector is not permitted.";
$l_sgcreate				= "Create New Sector Genesis Sector";
$l_sgcreatens				= "Create New Sector Genesis Link back to known space";
$l_sgns_forbid2            = "More than [limit] links in SG Sectors are not permitted.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "You do not have enough credits to create a new sector.";
$l_sgns_shipcredits            = "Credits on ship:";
$l_sgns_createcost            = "Cost to create new Sector:";
$l_sgns_complete            = "Normal Space Link Complete";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";
?>
