<?php
$l_nav_title             = "Navigations-Computer";
$l_nav_nocomp            = "Der Navigations-Computer ist nicht verfügbar";
$l_nav_query             = "Geben Sie den Sektor ein, zu dem der Weg gefunden werden soll: ";
$l_nav_pathfnd           = "Weg gefunden";
$l_nav_answ1             = "Er wird Sie führen";
$l_nav_answ2             = "turns um zu diesem Sektor zu gelangen.";
$l_nav_proper            = "Sie müssen Ihre Jäger-Bucht-Technologie erweitern bevor ihre Jäger die Warp-Route über diese Distanz finden können.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
