<?php
$l_novabomb_title             = "Warp Link Nova Bombe";
$l_novabomb_turns            = "Die Nova Bombe benötogt für den Abschuss mindestens 50 Turns.";
$l_novabomb_query             = "Sind Sie sicher, dass Sie den Sektor mit einer Nova Bomb beschiesen möchten?";
$l_novabomb_yes           = "Ja Nova Bombe abwerfen ";
$l_novabomb_question             = " um den Sektor zu bombardieren ";
$l_novabomb_success             = " wurde mit einer Nova Bombe beschossen!";
$l_novabomb_mines            = "[mines] Sector Minen zerstört.";
$l_novabomb_fighters            = "[fighters] Sektor-Jäger zerstört.";
$l_novabomb_planetsdamaged            = "Planeten von der Nova Bombe beschädigt";
$l_novabomb_planet            = "Planet ";
$l_novabomb_damage            = " hat Schaden von der Nova Bombe erlitten.";
$l_novabomb_shipsdamaged            = "Schiffe von der Nova Bombe beschädigt";
$l_novabomb_ship            = "Raumschiff ";
$l_novabomb_novaexplode   ="Die Nova Bombe explodierte beim Abschuss und hat dem Schiff massiven Schaden zugefügt.";
$l_novabomb_novaexplode2   ="Die Nova Bombe explodierte beim Abschuss und Ihr Schiff wurde zerstört.";
$l_novabomb_notfedsec   ="Die Nova Bombe kann in Sektoren der Föderation nicht benutzt werden.";
?>
