<?php
$l_lrs_title             = "Langstrecken-Scan";
$l_lrs_nofull            = "Ihre Scanner besitzen keine volle Langstrecken-Scan-Funktion.";
$l_lrs_noturns           = "Sie benötigen mindestens $fullscan_cost Turns um einen Langstrecken-Scan durch zufürhren.";
$l_lrs_used              = "gebraucht";
$l_lrs_turns             = "Turns";
$l_lrs_left              = "übrig";
$l_lrs_reach             = "Folgende Standorte können vom Sektor [sector] aus erreicht werden:";
$l_lrs_links             = "Links";
$l_lrs_ships             = "Schiffe";
$l_lrs_click             = "Klicken Sie einen der Links um zu diesem Sektor zu gelangen.";
$l_lrs_cantscan          = "Kann den angegebenen Sektor von diesem Sektor aus nicht scannen!";
$l_lrs_zero              = "Der Sektor 1 ist zu voll um nach Schiffen zu scannen!";
$l_lrs_moveto            = "um zum Sektor zu gelangen:";
$l_lrs_bounty            = "<font size=3 color='#ff0000'><b>Prämie</b></font>";
$l_log_titlet            = "Log ansehen";
$l_lrs_fedjammed           = "Die Föderation stört alle Sensoren-Scans.";
$l_lrs_imtitle             = "Der Sektor wird angegriffen";
$l_lrs_imbody             = "benutzt eine Sektor Nova auf";
$l_lrs_sectormissile_question             = " to fire sector missile.";
$l_log_months 		 = array('January','February','March','April','May','June','July','August','September','October','November','December');
$l_log_months_short 	 = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
?>
