<?php
$l_warp_linkto           = "Links von diesem Sektor führen nach";
$l_warp_nolink           = "Es gibt keine Links aus diesem Sektor.";
$l_warp_query            = "Zu welchem Sektor möchten Sie einen Link erstellen?";
$l_warp_oneway           = "Ein-Weg?";            
$l_warp_dest             = "Alternativ können Sie einen Link zerstören.";
$l_warp_destquery        = "Zu welchem Sektor soll der Link erntfernt werden?";
$l_warp_bothway          = "Zwei-Weg";
$l_warp_create          = "Erstelle einen Warplink zwischen Sektor: ";
$l_warp_andsector          = " und Sektor: ";
$l_warp_distance          = " mit eiener Entfernung von ";
$l_warp_lightyears          = " Lichtjahren";
$l_warp_delete          = "Lösche Warplink zwischen Sektor: ";
$l_warp_costcreate          = "Kosten für den Bau:";
$l_warp_costdelete          = "Kosten für die Entfernung:";
$l_warp_costenergy          = "Gebrauchte Energie: ";
$l_warp_twoerror         = "Der Gebrauch des Warp-Editors für einen Zweiwegelink zum Sektor [target_sector] ist nicht erlaubt.";
?>