<?php
// New News Items

$l_news_planets		 = " Planeten";
$l_news_cols		 = " Millionen Kolonisten";
$l_news_p_headline 	 = "[player]'s Empire hat nun [total] Planeten";
$l_news_c_headline 	 = "[player]'s Empire hat nun [total] Millionen Kolonisten";
$l_news_p_textXX	 = "The Federation has issued warnings concerning the Empire of [name].  [name] has control of [total] planets and should be considered very dangerous.  All sectors should increase sector defenses immediately.";
$l_news_c_textXX	 = "The Empire of [name] is experiencing massive overcrowding on all planets with over [total] million colonists.  Food shortages may cause unrest.  All sectors should be aware of possible aggressive actions by [name] in the future.";

$l_created_universe             = "Universum erstellt";
$l_created_universe_full        = "Wissenschaftler, die den Beginn des Universums erforschen haben einstimmig entschieden, das heute der wahrscheinlichste Tag ist, an dem die Erstellung eines neuen Universums stattfinden wird";

$l_news_p_text5		 = "Das wachsende Imperium von [name] hat nun fünf Planeten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten!";
$l_news_p_text10	 = "Das wachsende Imperium von [name] kontroliert nun stolze zehn Planeten. Berichte der FNN sagen, dass ein weiteres Wachstum von [name] zu einem Krieg führen könnte!";
$l_news_p_text25	 = "Das riesige Imperium von [name] hat bereits 25 Planeten kolonisiert. In einem Interview bestätigt [name], dass er in erwägung zieht, ein Wachstum für die Zukunft etwas zu verlangsamen!";
$l_news_p_text50	 = "Das enorm gigantische Imperium von [name], dass durch 50 Planeten in der ganzen Galaxy representiert wird hat eine bedrohliche Macht erreicht. Einer der Reporter von FNN hat herausgefunden, dass [name] sein Schiff aufrüstet und einen großen Krieg plant. In einem Interview mit [name] kündigte er an, dies Geschehe nur für die Verteidigung!";
$l_news_c_text25	 = "Das wachsende Imperium von [name] besitzt nun 25 Millionen Kolonisten. Die FNN wird seine weiteren Handlungen weiter für Sie im Auge behalten, aber es ist höchst wahrscheinlich, dass die Geburtenraten explodieren werden!";
$l_news_c_text100	 = "Das ehrgeizige Imperium von [name] hat nun 100 Million Kolonisten. Nach einer Explosion der Geburtenrate scheint es so, als seien [name]'s Kolonien ein guter Platz um eine Familie zu gründen!";
$l_news_c_text500	 = "Das große Imperium von [name] hat nun 500 million Kolonisten. [name] sagte in einem Interview, dass die Kolonisierung in dieser Galaxy erst am Anfang stehe";
$l_news_c_text1000	 = "Das gigantische Imperium von [name] hat eine Milliarden Kolonisten. FNN Reporter haben herausgefunden, dass [name] im Besitz von bizarren Klonmechanismen ist, die es ihm erlauben eine großer Zahl neuer Kolonisten zu erstellen. Mit dieser Zahl an Kolonisten ist die ökonomische Kraft seines Imperiums enorm. FNN hofft, dass [name] sein Geld nicht für die Kreigsführung verwendet";

$l_news_indi_short	 = "FNN munkelt: über [planets] Planeten erklären Ihre Unabhängigkeit.";
$l_news_indi	 = "FNN hat herausgefunden, dass über [planets] Planeten entschieden haben, dass Sie für sich alleine besser beherrscht werden und wurden unabhängig.";

$l_news_nova_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt.";
$l_news_nova	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bombe [total] Mal benutzt um einen Planeten und alle Schiffe darauf zu zerstören.";
$l_news_nova_m_short	 = "FNN Bericht: [name] hat eine Nova Bombe benutzt. Sein Ziel wurde aber verfehlt.";
$l_news_nova_m	 = "FNN's brandheise Neuigkeiten: Der Spieler [name] hat die gefürchtete Nova Bomb [total] Mal benutzt un versucht einen Planeten zu zerstören.  Die Nova Bombe explodierte ausserhalb der Atmosphere und verursachte erhebliche infrastrukturelle Schäden.";

$l_news_bounty	 = "FNN Report: [name] setzt eine Prämie von [amount] auf [name2] aus.";

$l_news_attackerpod_p_short	 = "FNN Bericht: [name]'s Schiff wurde zerstört.";
$l_news_attackerpod_P	 = "[name]'s wurde bei einem Angriff auf einen Planeten zerstört. Glücklicherweise hatte [name] eine Rettungskapsel und überlebte.";

$l_news_attackerdie_p_short	 = "FNN Bericht: [name] wurde getötet!";
$l_news_attackerdie_p	 = "[name]'s Schiff wurde bei einem Angriff auf einen Planeten zerstört. Sie sind umgekommen, weil Sie es versäumt hatten eine Rettungskapsel zu kaufen..";

$l_news_destroyed_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und vernichtet!";
$l_news_destroyed_p	 = "[name] hat [total] Planeten von [owner] angegriffen und. Die Bevölkerung jedes Planeten zerstörten ihn, um die Einahme des Planeten zu verhindern!";

$l_news_defeated_p_short	 = "FNN Bericht: [name] attackiert und besiegte einen Planeten!";
$l_news_defeated_p	 = "[name] attackierte [total] Planeten von [owner] und besiegte die planetarische Verteidigung!";

$l_news_notdefeated_p_short	 = "FNN Bericht: [name] hat einen Planeten angegriffen und verloren!";
$l_news_notdefeated_p	 = "[name] hat [total] Planeten von [owner] attackiert und die planetarische Verteidigung hielt gegen die unbarmherzigen Angriffe stand!";

$l_news_targetepod_short	 = "FNN Bericht: [name] attackiert [owner] und gewinnt!";
$l_news_targetepod	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Glücklicherweise hatte [owner] eine eingebaute Rettungskapsel und überlebte das ganze.";

$l_news_targetdies_short	 = "FNN Bericht: [name] attackiert [owner] und tötet ihn!";
$l_news_targetdies	 = "[name] attackiert [owner]'s Schiff und zerstörte es restlos. Schlimmerweise hatte [owner] keine Rettungskapsel und Sie wurden vaporisiert.";

$l_news_fedcolbounty_short	 = "FNN Report: The Federation cracks down on [name]!";
$l_news_fedcolbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which inflicted [amount] credits worth of damage on the pirate's vessel.  Federation officials promise further such actions in the future!";

$l_news_alliancecolbounty_short	 = "FNN Report: The Alliance cracks down on [name]!";
$l_news_alliancecolbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which inflicted [amount] credits worth of damage on the pirate's vessel.  Alliance officials promise further such actions in the future!";

$l_news_fedcol_pbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_pbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_pbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_pbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Alliance officials promise further such actions in the future!";

$l_news_fedcol_sbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_sbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated a ship ([shiptype]) worth [cost] in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_sbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_sbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated a ship [shiptype] worth [cost] in sector [sector].  Alliance officials promise further such actions in the future!";

$l_killheadline		 ="[target] wurde bei einem Unfall getötet";
$l_news_killed 		 = "[target] wurden heute bei einem tragischen Unglück getötet. Wie heroisch - Der Kapitän [target] war der letzte an Bord seines Schiffes, als er bemerkte, dass es keine Rettungskapsel gibt.";

$l_killSDheadline		 ="[target] was killed by Sector Defenses.";
$l_news_killedSD 		 = "[target] was killed by an overwhelming number of Sector Defenses owned by [killer]! Sadly, the ship was not equipped with an escape pod.";

$l_killplanetheadline		 ="[target] was killed attacking a planet.";
$l_news_killedplanet 		 = "[target] was killed while attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killshipheadline		 ="[target] was killed ship combat.";
$l_news_killedship 		 = "[target] was killed in ship to ship combat with [killer] today. The captain apparently forgot to equip the ship with an escape pod.";

$l_killsuicideheadline		 ="[target] commited suicide.";
$l_news_killedsuicide 		 = "[target] committed suicide today.  They took the cowards way out because they lacked the ability or courage to stand up to the pressures of commanding their own ship.";

$l_killsofaheadline		 ="[target] was killed sofa attacking a planet.";
$l_news_killedsofa 		 = "[target] was killed while sofa attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovaheadline		 ="[target] was killed during a nova attack.";
$l_news_killednova 		 = "[target] was killed by [killer] during a nova bomb attack today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovabackfireheadline		 ="[target] was killed from a nova backfire.";
$l_news_killednovabackfire 		 = "[target] was killed when their nova bomb backfired today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killsectormissileheadline		 ="[target] was killed from a Sector Missile.";
$l_news_killedsectormissile 		 = "[target] was killed when a Sector Missile from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killhunterprobeheadline		 ="[target] was killed from a Hunter Probe.";
$l_news_killedhunterprobe 		 = "[target] was killed when a Hunter Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killtrapprobeheadline		 ="[target] was killed from a Sentry Trap Probe.";
$l_news_killedtrapprobe 		 = "[target] was killed when a Sentry Trap Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

//-------------------

$l_killpodheadline		 ="[target]'s ship was destroyed in an accident";
$l_news_killedpod 		 = "[target]'s ship was destroyed in a tragic accident today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killSDpodheadline		 ="[target]'s ship was destroyed by Sector Defenses.";
$l_news_killedSDpod  		 = "[target]'s ship was destroyed by an overwhelming number of Sector Defenses owned by [killer]! An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killplanetpodheadline		 ="[target]'s ship was destroyed attacking a planet.";
$l_news_killedplanetpod  		 = "[target]'s ship was destroyed while attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killshippodheadline		 ="[target]'s ship was destroyed in ship combat.";
$l_news_killedshippod  		 = "[target]'s ship was destroyed in ship to ship combat with [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsofapodheadline		 ="[target]'s ship was destroyed while sofa attacking a planet.";
$l_news_killedsofapod  		 = "[target]'s ship was destroyed while sofa attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovapodheadline		 ="[target]'s ship was destroyed during a nova attack.";
$l_news_killednovapod  		 = "[target]'s ship was destroyed by [killer] during a nova bomb attack today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovabackfirepodheadline		 ="[target]'s ship was destroyed from a nova backfire.";
$l_news_killednovabackfirepod  		 = "[target]'s ship was destroyed when their nova bomb backfired today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsectormissilepodheadline		 ="[target]'s ship was destroyed by a Sector Missile.";
$l_news_killedsectormissilepod 		 = "[target]'s ship was destroyed when a Sector Missile from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killhunterprobepodheadline		 ="[target]'s ship was destroyed by a Hunter Probe.";
$l_news_killedhunterprobepod 		 = "[target]'s ship was destroyed when a Hunter Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killtrapprobepodheadline		 ="[target]'s ship was destroyed by a Sentry Trap Probe.";
$l_news_killedtrapprobepod 		 = "[target]'s ship was destroyed when a Sentry Trap Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline		 ="[name] has been promoted to [rank]";
$l_news_promoted 		 = "The Federation is pleased to announce the promotion of [name] to the rank of [rank].";

$l_news_demotedheadline		 ="[name] has been demoted to [rank]";
$l_news_demoted 		 = "The Federation regrets to announce the demotion of [name] to the rank of [rank].";

$l_news_namechangedheadline		 ="[oldname] changed name to [newname]";
$l_news_namechanged 		 = "[oldname] applied to the Federation Review Board to change their name to [newname].  The Federation has granted the name change.  From this day forward [oldname] shall now be known as [newname].  All ships and planets should update their records immediately.";

$l_news_found_planets_short	 = "Federation Survey: [found_planets] new planets located.";
$l_news_found_planets	 = "Federation Survey Scouts have located [found_planets] new planets in recently discovered sectors.";

$l_news_new_ports_short	 = "Federation Survey: [new_ports] new ports constructed.";
$l_news_new_ports	 = "Federation Engineers have constructed [new_ports] new ports in recently discovered sectors.";

$l_news_addedsectors_short	 = "Federation Survey: [addedsectors] sectors discovered.";
$l_news_addedsectors	 = "Federation Survey Scouts have discovered [addedsectors] new sectors.  Caution is advised.";

$l_news_artifactheadline		 ="[playername] completed [artifact]";
$l_news_artifact 		 = "[playername] has found all of the pieces of the [artifact] and has all of the power it can provide.";

$l_news_artifactfoundheadline		 ="[playername] found [artifact] piece";
$l_news_artifactfound 		 = "[playername] has found one of the pieces of the [artifact] and needs [pieces] more [piece].";

?>
