<?php
$l_pre_title             = "Ändere Realspace Presets";
$l_pre_exceed            = "Preset [preset] überschreitet das Maximum von [sector_max]. Keine presets gespeichert.<BR><BR>";
$l_pre_set               = "Preset";
$l_pre_save              = "Save";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
