<?php
$l_sendm_title           = "Nachricht senden";
$l_sendm_to              = "To";
$l_sendm_from            = "From";
$l_sendm_ally            = "Team:";
$l_sendm_subj            = "Betreff";
$l_sendm_mess            = "Nachricht";
$l_sendm_send            = "Senden";
$l_sendm_sent            = "Nachricht verschickt";
$l_sendm_blocked            = " hat Sie am versenden gehindert.";
$l_sendm_blockmanager            = "Nachrichten Block-Manager";
?>
