<?php
$l_profile_title = "Profilregistrierung";
$l_profile_notenabled = "Profile sind auf diesem Server nicht aktiviert.";
$l_profile_registered = "Dieser Spieler ist nun auf dem Master Profil-Server registriert.";
$l_profile_nomatch = "Es konnte kein Profil mit dem selben Namen und Passwort auf dem Master Profil-Server gefunden werden.";
$l_profile_tryagain = "Geben Sie ihren Namen und ihr Passwort erneut ein, um Zutritt zu ihrem Profil zu erhalten.";
$l_profile_name = "Spieler Name";
$l_profile_password = "Passwort des Profil-Servers";
$l_profile_bannedserver = "Dieser Server hat keine Befugnis, dem Master-Server Profil-Informationen zu zusenden.";
$l_profile_bannedplayer = "Sie wurden vom Master Profil-Server gebannt.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "This server <b><u>REQUIRES</u></b> every new player to have a registered profile.  You will not be allowed to create a new player unless you do have a registered profile.";
$l_profile_updated = "Your template, shoutbox and news crawl global settings have been updated on the Profile Master Server.  These settings will automatically be used when you register your profile on any game.";

?>