<?php
$l_gns_title             = "Genesis Device benutzten";
$l_gns_turn              = "Sie benötigen mindestens einen Turn, um das Genesis device zu benutzten.";
$l_gns_onplanet          = "Sie können das Gerät nicht verwenden, während sich sich auf der Planetenoberfläche befinden.";
$l_gns_full              = "Dieses Sonnensystem ist schon voll.";
$l_gns_planetex          = "Es gibt bereits einen Planeten in diesem Sektor.";
$l_gns_nogenesis         = "Sie haben kein Genesis device.";
$l_gns_forbid            = "Das Erstellen eines Planeten in diesem Sektor ist nicht gestattet.";
$l_gns_bforbid           = "Die Basen in diesem Sektor stören sich mit Ihrem Genesis device. Der Planet konnte nicht erstellt werden.";
$l_gns_pcreate           = "Der Planet wurde erstellt.";
$l_sgns_title             = "Benutzung des Sektor Genesis Device";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "Sie haben kein Sector Genesis device.";
$l_sgns_forbid            = "Das Erstellen eines neuen Sektor Genesis Wurmloches in diesem Sektor ist nicht erlaubt.";
$l_sgns_forbid1            = "Das Erstellen eines Sektor Genesis Wurmloches im Sektor der Föderation ist nicht erlaubt.";
$l_sgcreate				= "Erstelle einen neuen Sektor Genesis Sektor";
$l_sgcreatens				= "Erstelle einen neuen Sektor Genesis Link zurück zu bekanntem Weltraum";
$l_sgns_forbid2            = "Mehr als [limit] Links in SG Sektoren ist nicht erlaubt.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "Sie haben nicht genügend Credits um einen neuen Sektor zu erstellen.";
$l_sgns_shipcredits            = "Credits auf dem Schiff:";
$l_sgns_createcost            = "Kosten für das Erstellen eines neuen Sektors:";
$l_sgns_complete            = "Normal-Wetraum-Link fertig gestellt.";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";

?>
