<?php
$l_casino_title	=	"Kasino";
$l_casino_welcome	=	"Willkommen im Kasino. Wir bieten zur Zeit folgende Spiele und Ausstattungen an";
$l_casino_option	=	"Räume";
$l_casino_detail	=	"Beschreibung";

// Blackjack
$l_bet		=	"Wette";
$l_stand	=	"Stand";
$l_hit		=	"Treffer";
$l_firsthand		=	"aus erster Hand";
$l_secondhand		=	"aus zweiter Hand";
$l_insurance = 	"Versicherung";
$l_doubledown = "Double Down";
$l_lobby	=	"Lobby";
$l_split 	=   "Aufteilung";
$l_credits  =   "Credits";
$l_yourbet	=	"Deine Wette";
$l_nobet	=	"Deien Wette hat deine Credits überschritten. Bitte wette nochmal.";
$l_dealerwins = "Der Hänler hat gewonnen!";
$l_dealerbust = "Der Händler hat pleite gemacht!";
$l_dealerloses = "Der Händler hat verloren!";
$l_dealerblackjack ="Händler Totschläger!";
$l_push		= "Anstoß";
$l_playerwins	=	"Der Spieler hat gewonnen!";
$l_playerbust	=	"Der Spieler hat pleite gemacht!";
$l_playerloses	=	"Der Spieler hat verloren!";
$l_playerblackjack	=	"Spieler Totschläger!";
$l_place_bet	=	"Plaziere deine Wette";
?>