<?php
$l_profile_title = "Registratione Profilo";
$l_profile_notenabled = "I Profili non sono abilitati su questo server.";
$l_profile_registered = "Questo giocatore è ora registrato con il Master Profile Server.";
$l_profile_nomatch = "Non è stato possibile trovare un profilo sul Master Profile Server con il nome e la server password immessi.";
$l_profile_tryagain = "Per inserire di nuovo il nome e la server password del profilo clicca ";
$l_profile_name = "Nome Profilo Giocatore";
$l_profile_password = "Server Password del profilo";
$l_profile_bannedserver = "Questo server non è abilitato a inviare informazioni di profili al Master Profile Server.";
$l_profile_bannedplayer = "Sei stato bannato dal Master Profile Server e non puoi registrare giocatori.";
$l_profile_description = "If you have registered a Player Profile at <a href=\"http://www.aatraders.com\" target=\"_blank\">http://www.aatraders.com</a> you should enter your Player Profile Name and Profile Server Password.  This will automatically register your account on this server with the Player Profile Server.  All of your game statistics will be automatically updated when you finish playing.";
$l_profile_required = "This server <b><u>REQUIRES</u></b> every new player to have a registered profile.  You will not be allowed to create a new player unless you do have a registered profile.";
$l_profile_updated = "Your template, shoutbox and news crawl global settings have been updated on the Profile Master Server.  These settings will automatically be used when you register your profile on any game.";

?>