<?php
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] ha colpito [chm_roll] mine nel settore [chm_sector].";         
$l_chm_youlostminedeflectors    = "Hai perso [chm_roll] deflettori di mine.";
$l_chm_youlostallminedeflectors = "Hai perso tutti i tuoi deflettori di mine.";
$l_chm_youhadnominedeflectors  = "Non hai deflettori di mine.";
$l_chm_yourshieldshitforminesdmg        = "I tuoi scudi hanno subito [chm_mines_left] danni.";
$l_chm_yourshieldsaredown       = "I tuoi scudi sono a zero!";
$l_chm_youlostallyourshields    = "Hai perso gli scudi!";
$l_chm_yourarmorhitforminesdmg  = "La tua armatura ha subito [chm_mines_left] danni.";
$l_chm_yourhullisbreached       = "Lo scafo della tua nave è stato penetrato!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] è stato distrutto dalle tue mine nel settore [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "La tua nave è stata distrutta!";
$l_chm_luckescapepod     = "Fortunatamente avevi una capsula di salvataggio!";

$l_chm_yourdeflectormalf1		 = "Mine Deflector launching system has malfunctioned.";
$l_chm_yourdeflectormalf2		 = "You have only been able to launch ";
$l_chm_yourdeflectormalf3		 = " percent of your mine deflectors.";
$l_chm_enemytorpfailshields     = " hasn't launched any torpedoes against your shields.";
$l_chm_enemytorpfailarmor     = " hasn't launched any torpedoes against your armor.";

$l_chm_minemalf1		 = "Enemy Mines have malfunctioned.";
$l_chm_minemalf2		 = "Only ";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines   = "You hit [chm_roll] mines out of [total_mines] mines!";
$l_chm_yourdeflectormalf2a		 = "You have only been able to launch [deflectors] percent of your mine deflectors.";
$l_chm_mines_destroyed		 = "[number] of [target] mines have been destroyed!";
$l_chm_mine_deflectors_left		 = "You have [number] mine deflectors left.";
$l_chm_mines_left		 = "There are [number] mines left and they are impacting upon your armor!";
$l_chm_minemalf2a		 = "Only [deflectors] percent of the mines attacking found your ship.";
$l_chm_mines_exhausted		 = "[player] Mines Exhausted!";
$l_chm_armor_left		 = "You have [number] armor points left!";

?>
