<?php
$l_login_title			= "Login";
$l_login_pw			= "Password:";
$l_login_chooseres		= "Impossibile determinare la risoluzione del tuo schermo. Seleziona la risoluzione migliore per te:";
$l_login_newp			= "Se sei un nuovo giocatore, clicca <A HREF=\"new_player.php\">qui</A>.";
$l_login_prbs			= "Problemi?";   
$l_login_emailus		= "scrivici via E-mail";
$l_login_forgot_pw		= "Hai scordato la tua password? Lascia il campo vuoto, e clicca su Login.";
$l_login_settings 		= "Settaggi del Gioco";
$l_login_change			= "Cambia";
$l_login_title2			= "Login per AATraders";
$l_login_reset1			= "Nessun Reset previsto";
$l_login_reset2			= "Reset programmato: ";
$l_login_reset3			= "Reset previsto: ";
$l_login_notice			= "Notizia Importante:";
$l_login_endadminnews			= "Fine News Amministratore";
$l_login_tourney_signup = "Tournament Signups Enabled";

$l_login_profile_only		= "Profile Only";       
$l_login_newclosed_message		= "New Signups Closed";                
$l_login_tourneymode		= "Tournament Running";                
$l_login_tourneystarts		= "Starts: ";                
?>
