<?php
$l_chf_youretreatback    = "Ti sei ritirato verso il settore da dove sei arrivato";
$l_chf_movefailed        = "Mossa fallita.";
$l_chf_thefightersdetectyou     = "I Droni ti hanno scoperto!";
$l_chf_therearetotalfightersindest      = "Ci sono [chf_total_sector_fighters] droni nel settore di destinazione.";
$l_chf_youcanretreat     = "<B>Ritirata</B> - Ti costerà un'altra mossa.";
$l_chf_inputfight        = "<B>Attacco</B> - Devi sconfiggere tutti i Droni per entrare nel settore.";
$l_chf_inputcloak        = "<B>Occultamento</B> - Usa il tuo occultamento e cerca di evadere i Droni.";
$l_chf_go                = "Vai";
$l_chf_inputrun        = "<B>Attack and Run</B> - You do a lightening attack run and retreat.  But you MAY take some damage during retreat.";
?>
