<?php
$l_nav_title             = "Computer di Navigazione";
$l_nav_nocomp            = "Il Computer di Navigazione non è disponibile";
$l_nav_query             = "Inserisci il settore per il quale si deve trovare il percorso: ";
$l_nav_pathfnd           = "Percorso trovato";
$l_nav_answ1             = "Ti costerà";
$l_nav_answ2             = "turni per andare in tale settore.";
$l_nav_proper            = "La tecnologia del tuo computer è troppo primitiva per calcolare un percorso di Rotte warp verso tale settore.";
$l_nav_autoroutename     = "Optional Autoroute Name: ";
$l_nav_manuallist        = "Manually Built WarpLink Autoroute List";
$l_nav_warplinksleaving     = "Warp Links Leaving [sector_name]";
$l_nav_nowarplinksleaving     = "There are no warplinks leaving this sector.";
$l_nav_warp_from           = "Warp from";
$l_nav_rs_from            = "RSMove from";
$l_nav_notinlogs            = "No data available on this sector.";
?>
