<?php
$l_shout_title            = "Shout Box";
$l_shout_title2              = ".:: SHOUTBOX ::.";
$l_shout_public         = "Pubblico";
$l_shout_team             = "Squadra";
$l_shout_smiles            = "Smiles";
$l_shout_else          = "altrimenti";
$l_shout_refresh          = "Aggiorna";
$l_shout_close          = "Chiudi finestra";
$l_shout_saved          = "Shout salvato!";
$l_shout_return          = "Ritorna al ";
$l_shout_prev = "Previous";
$l_shout_next = "Next";
$l_shout_selectpage = "Select Page";
$l_shout_page = "Page: ";
$l_shout_teamtitle              = ".:: TEAM SHOUTBOX ::.";
?>