<?php

// Confirmed common to multiple files:

$l_zname[1] 		 = "Spazio non mappato";
$l_zname[2] 		 = "Spazio della Federazione";
$l_zname[3] 		 = "Spazio della Alliance";
$l_zname[4] 		 = "Zona di guerra";

$l_nova 		 = "Nova";
$l_nova 		 = "Bomba Nova";
$l_lssd 		 = "Dispositivo Ultima Nave Avvistata";
$l_lss 			 = "Ultima nave vista in questo settore";

// Common to : warpedit 1-3.php

$l_warp_title		 = "Editor Warp";
$l_warp_turn		 = "Hai bisogno di almeno un turno per utilizzare un Editor Warp.";
$l_warp_none		 = "Non hai alcun Editor Warp.";
$l_warp_forbid		 = "In questo settore non è permesso utilizzare Editor Warp.";
$l_swarp_forbid		 = "Non è permesso utilizzare Editor Warp verso o da settori SG.";
$l_warp_nosector	 = "Il settore indicato non esiste.";

// Not yet confirmed common to multiple files:

$l_yes 			 = "Si";
$l_no			 = "No";
$l_here			 = "qui";
$l_submit		 = "Invia";
$l_reset		 = "Azzera";
$l_all			 = "Tutti";

$l_trade		 = "Trade";
$l_ore			 = "Metallo";
$l_commodity		 = "Commodity";
$l_commodities		 = "Merci";
$l_organics		 = "Organici";
$l_goods		 = "Prodotti";
$l_energy		 = "Energia";
$l_colonists		 = "Coloni";
$l_credits 		 = "Crediti";
$l_units		 = "unità di ";
$l_special		 = "Speciale";
$l_upgrade_ports	 = "Potenziamenti";
$l_device_ports		 = "Dispositivi";
$l_spacedock		 = "Spazioporto";
$l_casino		 = "Casino";
$l_spy = "Spie";
$l_dig = "Dignitari";

$l_cargo		 = "Cargo";
$l_fighters		 = "Droni ";
$l_mines		 = "Mine ";
$l_torps		 = "Siluri";

$l_none			 = "Nessuno";
$l_unnamed		 = "senza nome";
$l_name			 = "Nome";
$l_unowned		 = "di nessuno";
$l_unknown		 = "sconosciuto";
$l_clickme 		 = "Clicca qui";
$l_player  		 = "Giocatore";
$l_ship			 = "Nave";
$l_ships		 = "Navi";
$l_set			 = "set";
$l_realspace		 = "Spazio Reale";
$l_armorpts		 = "Punti armatura";
$l_links		 = "Rotte";
$l_login_email          = "Indirizzo E-mail:";
$l_add			 = "Aggiungi";
$l_teamforum			 = "Forum della Squadra";
$l_teamships			 = "Navi della Squadra";
$l_tutorial			 = "Tutorial/Aiuto";
$l_avatar			 = "Avatar";
$l_teamicon			 = "Icona della Squadra";
$l_debris			 = "Rottami";
$l_localmap			 = "Mappa locale";
$l_arm_weap              = "Armatura & Armi";
$l_3dmap			 = "Mappa 3D della galassia";

$l_max = "Max";
$l_casino = "Casino";

$l_sectormissile = "Sector Missile";
$l_spacebeacon = "Boa Spaziale";
$l_spaceprobes = "Sonde Spaziali";
$l_warpeditors = "Editor Warp";
$l_genesistorps = "Siluri Genesis";
$l_sgtorps = "Siluri SG";
$l_minesfighters = "Mine/Droni";
$l_ewarp = "Dispositivo d'emergenza Warp";
$l_reports = "Rapporti";
$l_shipinfo = "Info Nave";
$l_sectornotes = "Note di Settore";
$l_maps = "Mappe";
$l_messages = "Messaggi";
$l_shiptype = "Tipo Nave";
$l_help = "Aiuto";
$l_rank = "Rango";
$l_teamplanets = "Pianeti della Squadra";
$l_teamdefenses = "Difese della Squadra";
$l_planetstatus = "Stato Pianeti";
$l_planetdefenses = "Difese Planetarie";
$l_changeproduction = "Cambia Produzione";
$l_galacticarm = "Braccio Galattico";
$l_armor = "Armatura";
$l_news_none             = "Spiacente, nessuna notizia oggi.";

$l_ranks_good            = "Good";
$l_ranks_evil            = "Evil";
$l_ranks_neutral       = "Neutral";

$l_global_mmenu          ="Clicca <A HREF=main.php>qui</A> per tornare al Menu Principale.";
$l_global_mlogin         ="Clicca <A HREF=index.php>qui</A> per tornare alla schermata di Login.";
$l_global_needlogin      ="Devi loggarti, clicca <A HREF=index.php>qui</A>.";
$l_global_died           ="Il personaggio è morto! Ecco <a href=log.php>qui</a> cosa è successo<BR><BR>Avrai più fortuna la prossima volta!";
$l_global_warzone        ="La Zona è ora una Zona di Guerra!";
$l_global_nzone          ="La Zona è ora neutrale.";
$l_global_team           ="La Zona appartiene ora al team";
$l_global_player         ="La Zona appartiene ora al giocatore";
$l_global_nochange       ="La proprietà della Zona non è cambiatax";
$l_insignia[0]           = "1c.png";
$l_insignia[1]           = "2c.png";
$l_insignia[2]           = "3c.png";
$l_insignia[3]           = "4c.png";
$l_insignia[4]           = "o-1.png";
$l_insignia[5]           = "o-2.png";
$l_insignia[6]           = "o-3.png";
$l_insignia[7]           = "o-4.png";
$l_insignia[8]           = "o-5.png";
$l_insignia[9]           = "o-6.png";
$l_insignia[10]          = "o-7.png";
$l_insignia[11]          = "o-8.png";
$l_insignia[12]          = "o-9.png";
$l_insignia[13]          = "o-10.png";
$l_insignia[14]          = "o-11.png";
$l_insignia[15]          = "o-12.png";
$l_insignia[16]          = "o-13.png";
$l_insignia[17]          = "o-14.png";
$l_insignia[18]          = "o-15.png";
$l_insignia[19]          = "o-16.png";

$l_insignia_name[0]           = "Spaceman Recruit";
$l_insignia_name[1]           = "Spaceman Apprentice";
$l_insignia_name[2]           = "Spaceman";
$l_insignia_name[3]           = "Petty Officer Third Class";
$l_insignia_name[4]           = "Petty Officer Second Class";
$l_insignia_name[5]           = "Petty Officer First Class";
$l_insignia_name[6]           = "Chief Petty Officer";
$l_insignia_name[7]           = "Senior Chief Petty Officer";
$l_insignia_name[8]           = "Master Chief Petty Officer";
$l_insignia_name[9]           = "Ensign";
$l_insignia_name[10]          = "Lieutenant Junior Grade";
$l_insignia_name[11]          = "Lieutenant";
$l_insignia_name[12]          = "Lieutenant Commander";
$l_insignia_name[13]          = "Commander";
$l_insignia_name[14]          = "Captain";
$l_insignia_name[15]          = "Rear Admiral (lower half)";
$l_insignia_name[16]          = "Rear Admiral (upper half)";
$l_insignia_name[17]          = "Vice Admiral";
$l_insignia_name[18]          = "Admiral";
$l_insignia_name[19]          = "Fleet Admiral";

$l_main_title            = "Menu Principale";
$l_main_warpto           = "Rotta Warp verso";
$l_main_autoroute        = "Auto-Rotta verso";
$l_main_rs_to            = "Spazioreale verso";
$l_main_other            = "Altri";
$l_main_shipyard1        = "Hangar Spaziale";
$l_main_shipyard2        = "Accedi all' ";
$l_traderoutes           = "Rotte Commerciali";
$l_trade_control         = "Gestione Rotte";
$l_youhave               = "Hai ";
$l_turns_used            = "Turni usati: ";
$l_turns_have            = "Turni a disposizione: ";
$l_score                 = "Punteggio: ";
$l_sector                = "Settore";
$l_help                  = "Aiuto";
$l_faq                   = "FAQ";
$l_feedback              = "Feedback";
$l_forums                = "Forum";
$l_logout                = "Esci";
$l_commands              = "Comandi";
$l_command_no            = "Comando non disponibile.";
$l_devices               = "Dispositivi";
$l_planets               = "Pianeti";
$l_log                   = "Diario";
$l_sector_def            = "Difese del settore";
$l_defense               = "Difese";
$l_read_msg              = "Leggi messaggi";
$l_send_msg              = "Invia messaggi";
$l_rankings              = "Classifica";
$l_teams                 = "Squadre";
$l_ohno                  = "Autodistruzione";
$l_options               = "Opzioni";
$l_navcomp               = "Computer di navigazione";
$l_incompletemove        = "Non hai completato la mossa precedente.";
$l_clicktocontinue       = "Clicca qui per continuare";
$l_toplanetmenu          = "per andare al menu del pianeta.";
$l_nonexistant_pl        = "Su un pianeta che non esiste?!?";
$l_abord                 = ", a bordo della nave ";
$l_messages_wait         = " messaggi non letti.";
$l_no_warplink           = "Nessuna rotta warp";
$l_scan                  = "scan";
$l_fullscan              = "Scan completo";
$l_port                  = "Porto";
$l_tradingport           = "Porto commerciale";
$l_planet_in_sec         = "Pianeti nel settore ";
$l_ships_in_sec          = "Altre navi nel settore ";
$l_sector_0              = "C'è così tanto traffico in Sol che non riesci nemmeno a distinguere le altre navi!";
$l_map                   = "Mappa";
$l_probe				 = "Sonde";
$l_autotrade				 = "Auto-Rotte";
$l_onboard				 = "a bordo di una nave classe";
$l_classship = ".";
$l_traveled = "ha viaggiato verso il settore";
$l_max_planets = "Massimo numero di pianeti abitabili";
$l_block_msg              = "Blocca i messaggi";
$l_sectorinfo               = "Sector Info";
$l_add_note="Add Note";
$l_view_note="View";
$l_notes="Notes";
$l_global_limitreached="You have reached the limit for the amount of time you are allowed to be online each day.  Log in again tomorrow after midnight.";
$l_onlinetimeleft = "Remaining Time:";
$l_planetmax = "Planetary Maximum:";
$l_storedshipreport = "Stored Ships";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federation Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader's Lobby";

$l_common_prev="Previous Page";
$l_common_next="Next Page";
$l_common_totalpages="Total Pages";
$l_common_selectpage="Select Page: ";
$l_common_page="Page: ";
$l_templatechange = "Would you like to keep this Template?";

$l_im_fed_bounty = "The Federation has placed a bounty on you for attacking such a low ranked player.  The Federation will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_fed_bounty_title = "Federation placed a Bounty on you!";
$l_im_alliance_bounty = "The Alliance has placed a bounty on you for attacking such a low ranked player.  The Alliance will attack your ship on a regular basis until you pay back your bounty.  You can pay off your bounty at any Upgrade Port or Spacedock.";
$l_im_alliance_bounty_title = "Alliance placed a Bounty on you!";
$l_instant_messages_waiting = "You have [count] messages waiting for you.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Filled: ";
$l_hold_space_free = "Holds Empty: ";
$l_port_buys = "Port Buys: ";

?>
