<?php
// New News Items

$l_news_planets		 = " pianeti";
$l_news_cols		 = " milioni di coloni";
$l_news_p_headline 	 = "L'impero di [player] ha ora [total] pianeti";
$l_news_c_headline 	 = "L'impero di [player] ha ora [total] milioni di coloni";
$l_news_p_textXX	 = "The Federation has issued warnings concerning the Empire of [name].  [name] has control of [total] planets and should be considered very dangerous.  All sectors should increase sector defenses immediately.";
$l_news_c_textXX	 = "The Empire of [name] is experiencing massive overcrowding on all planets with over [total] million colonists.  Food shortages may cause unrest.  All sectors should be aware of possible aggressive actions by [name] in the future.";

$l_created_universe             = "Creazione dell'universo";
$l_created_universe_full        = "Scienzati che studiano l'inizio della vita dell'universo, hanno deciso all'unanimità che oggi è statisticamente il giorno più probabile in cui potrebbe essere avvenuta la Creazione dell'Universo";

$l_news_p_text5		 = "Il nascente impero di [name] ora è costituito da cinque pianeti, la FNN osserverà le azioni di [name] più attentamente in futuro!";
$l_news_p_text10	 = "Il crescente impero di [name] ora controlla dieci pianeti. I rapporti della FNN riferiscono che un'ulteriore espansione di [name] potrebbe causare guerre!";
$l_news_p_text25	 = "Il vasto impero di [name] possiede 25 pianeti colonizzati. In un'intervista [name] ha annunciato che potrebbe decidere di ridurre il tasso di espansione in futuro!";
$l_news_p_text50	 = "Il gigantesco impero di [name], costituito da 50 pianeti nella galassia, rappresenta una forza considerevole. Un reporter della FNN ha scoperto che [name] sta potenziando la propria nave pianificando battaglie di conquista. In un'intervista [name] ha annunciato che lo fa per soli scopi difensivi!";
$l_news_c_text25	 = "Del nascente impero di [name] fanno parte 25 millioni di coloni, la FNN osserverà le azioni di [name] più attentamente in futuro, ma è ovvio che i tassi di natalità stanno per esplodere!";
$l_news_c_text100	 = "Il futuro impero di [name] ora ha 100milioni di coloni; dopo un'esplosione dei tassi di natalità, le colonie di [name] sembrano un buon posto dove le famiglie possono insediarsi!";
$l_news_c_text500	 = "Il grande impero di [name] è abitato da 500 milioni di  coloni; [name] ha detto in un'intervista che la colonizzazione della galassia è appena cominciata!";
$l_news_c_text1000	 = "L'affollato impero di [name] è ora costituito da un miliardo di coloni. Reporter della FNN hanno scoperto che [name] è in possesso di qualche esotico dispositivo di clonazione che gli permette di sfamare i numerosi nuovi coloni. Con questo numero di abitanti, la potenza economica dell'impero è enorme. La FNN spera che [name] non spenda i suoi soldi in armamenti bellici";

$l_news_indi_short	 = "FNN - Soffiata: oltre [planets] si dichiarano indipendenti.";
$l_news_indi	 = "Fonti della FNN riferiscono che oltre [planets] pianeti hanno deciso che preferisono governarsi da soli, e si sono dichiarati indipendenti.";

$l_news_nova_short	 = "FNN - Rapporto: [name] usa una Bomba Nova.";
$l_news_nova	 = "Fonti della FNN riportano che [name] ha usato una Bomba Nova [total] volta/e per distruggere un pianeta e tutte le navi su di esso.";
$l_news_nova_m_short	 = "FNN - Rapporto: [name] usa una Bomba Nova, ma manca il bersaglio.";
$l_news_nova_m	 = "Fonti della FNN riportano che [name] ha cercato di usare una Bomba Nova [total] volta/e per distruggere un pianeta , ma questa è esplosa fuori dall'atmosfera, causando ingenti danno alle infrastrutture del pianeta.";

$l_news_bounty	 = "FNN - Rapporto: [name] piazza una taglia di [amount] crediti su [name2].";

$l_news_attackerpod_p_short	 = "FNN - Rapporto: [name] ha perso la nave.";
$l_news_attackerpod_P	 = "La nave di [name] è stata distrutta mentre attaccava un pianeta. Fortunatamente [name] aveva una capsula di salvataggio ed è sopravvissuto.";

$l_news_attackerdie_p_short	 = "FNN - Rapporto: [name] è morto!";
$l_news_attackerdie_p	 = "La nave di [name] è stata distrutta mentre attaccava un pianeta, e non avendo una capsula di salvataggio è rimasto ucciso.";

$l_news_destroyed_p_short	 = "FNN - Rapporto: [name] attacca e distrugge un pianeta!";
$l_news_destroyed_p	 = "[name] ha attaccato [total] volte un pianeta di [owner], infine sconfiggendolo; gli abitanti hanno deciso di distruggere le loro case, piuttosto che vederle catturate da [name]!";

$l_news_defeated_p_short	 = "FNN - Rapporto: [name] attacca e sconfigge un pianeta!";
$l_news_defeated_p	 = "[name] ha attaccato [total] volte un pianeta di [owner] e alla fine ha sconfitto le difese planetarie!";

$l_news_notdefeated_p_short	 = "FNN - Rapporto: [name] attacca un pianeta e perde!";
$l_news_notdefeated_p	 = "[name] ha attaccato [total] volte un pianeta di [owner] e le difese planetarie hanno resistito e sconfitto l'attaccante!";

$l_news_targetepod_short	 = "FNN - Rapporto: [name] attacca la nave di [owner] e vince!";
$l_news_targetepod	 = "[name] ha attaccato la nave di [owner] e l'ha distrutta completamente.  Fortunatamente [owner] aveva una capsula di salvataggio ed è sopravvissuto.";

$l_news_targetdies_short	 = "FNN - Rapporto: [name] attacca la nave di [owner] e la distrugge!";
$l_news_targetdies	 = "[name] ha attaccato la nave di [owner] e l'ha distrutta completamente. Sfortunatamente [owner] mom aveva una capsula di salvataggio ed è stato vaporizzato nello spazio.";

$l_news_fedcolbounty_short	 = "FNN Report: The Federation cracks down on [name]!";
$l_news_fedcolbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which inflicted [amount] credits worth of damage on the pirate's vessel.  Federation officials promise further such actions in the future!";

$l_news_alliancecolbounty_short	 = "FNN Report: The Alliance cracks down on [name]!";
$l_news_alliancecolbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which inflicted [amount] credits worth of damage on the pirate's vessel.  Alliance officials promise further such actions in the future!";

$l_news_fedcol_pbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_pbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_pbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_pbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated the planet [planetname] worth [amount] credits in sector [sector].  Alliance officials promise further such actions in the future!";

$l_news_fedcol_sbounty_short	 = "FNN Report: The Federation hunts down [name]!";
$l_news_fedcol_sbounty	 = "The Federation today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Federation battlecruiser, which confiscated a ship ([shiptype]) worth [cost] in sector [sector].  Federation officials promise further such actions in the future!";

$l_news_alliancecol_sbounty_short	 = "FNN Report: The Alliance hunts down [name]!";
$l_news_alliancecol_sbounty	 = "The Alliance today has cracked down on the notorious space pirate [name]!  [name], who routinely violated several space treaties, was briefly engaged by the Alliance, which confiscated a ship [shiptype] worth [cost] in sector [sector].  Alliance officials promise further such actions in the future!";

$l_killheadline		 ="[target] è stato ucciso in un incidente";
$l_news_killed 		 = "[target] è stato ucciso in un tragico incidente. Eroicamente il capitano [target] ha aspettato che tutto l'equipaggio lasciasse la nave, quando ha notato che non c'era una scialuppa di salvataggio anche per lui. Possa riposare in pace!";

$l_killSDheadline		 ="[target] was killed by Sector Defenses.";
$l_news_killedSD 		 = "[target] was killed by an overwhelming number of Sector Defenses owned by [killer]! Sadly, the ship was not equipped with an escape pod.";

$l_killplanetheadline		 ="[target] was killed attacking a planet.";
$l_news_killedplanet 		 = "[target] was killed while attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killshipheadline		 ="[target] was killed ship combat.";
$l_news_killedship 		 = "[target] was killed in ship to ship combat with [killer] today. The captain apparently forgot to equip the ship with an escape pod.";

$l_killsuicideheadline		 ="[target] commited suicide.";
$l_news_killedsuicide 		 = "[target] committed suicide today.  They took the cowards way out because they lacked the ability or courage to stand up to the pressures of commanding their own ship.";

$l_killsofaheadline		 ="[target] was killed sofa attacking a planet.";
$l_news_killedsofa 		 = "[target] was killed while sofa attacking a planet owned by [killer] today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovaheadline		 ="[target] was killed during a nova attack.";
$l_news_killednova 		 = "[target] was killed by [killer] during a nova bomb attack today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killnovabackfireheadline		 ="[target] was killed from a nova backfire.";
$l_news_killednovabackfire 		 = "[target] was killed when their nova bomb backfired today. Unfortunately, the ship was not equipped with an escape pod.";

$l_killsectormissileheadline		 ="[target] was killed from a Sector Missile.";
$l_news_killedsectormissile 		 = "[target] was killed when a Sector Missile from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killhunterprobeheadline		 ="[target] was killed from a Hunter Probe.";
$l_news_killedhunterprobe 		 = "[target] was killed when a Hunter Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

$l_killtrapprobeheadline		 ="[target] was killed from a Sentry Trap Probe.";
$l_news_killedtrapprobe 		 = "[target] was killed when a Sentry Trap Probe from [killer] impacted their shields. Unfortunately, the ship was not equipped with an escape pod.";

//-------------------

$l_killpodheadline		 ="[target]'s ship was destroyed in an accident";
$l_news_killedpod 		 = "[target]'s ship was destroyed in a tragic accident today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killSDpodheadline		 ="[target]'s ship was destroyed by Sector Defenses.";
$l_news_killedSDpod  		 = "[target]'s ship was destroyed by an overwhelming number of Sector Defenses owned by [killer]! An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killplanetpodheadline		 ="[target]'s ship was destroyed attacking a planet.";
$l_news_killedplanetpod  		 = "[target]'s ship was destroyed while attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killshippodheadline		 ="[target]'s ship was destroyed in ship combat.";
$l_news_killedshippod  		 = "[target]'s ship was destroyed in ship to ship combat with [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsofapodheadline		 ="[target]'s ship was destroyed while sofa attacking a planet.";
$l_news_killedsofapod  		 = "[target]'s ship was destroyed while sofa attacking a planet owned by [killer] today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovapodheadline		 ="[target]'s ship was destroyed during a nova attack.";
$l_news_killednovapod  		 = "[target]'s ship was destroyed by [killer] during a nova bomb attack today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killnovabackfirepodheadline		 ="[target]'s ship was destroyed from a nova backfire.";
$l_news_killednovabackfirepod  		 = "[target]'s ship was destroyed when their nova bomb backfired today. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killsectormissilepodheadline		 ="[target]'s ship was destroyed by a Sector Missile.";
$l_news_killedsectormissilepod 		 = "[target]'s ship was destroyed when a Sector Missile from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killhunterprobepodheadline		 ="[target]'s ship was destroyed by a Hunter Probe.";
$l_news_killedhunterprobepod 		 = "[target]'s ship was destroyed when a Hunter Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

$l_killtrapprobepodheadline		 ="[target]'s ship was destroyed by a Sentry Trap Probe.";
$l_news_killedtrapprobepod 		 = "[target]'s ship was destroyed when a Sentry Trap Probe from [killer] impacted their shields. An Escape Pod transponder was detected by Federation Search and Rescue.";

// --------------------------

$l_news_promotedheadline		 ="[name] has been promoted to [rank]";
$l_news_promoted 		 = "The Federation is pleased to announce the promotion of [name] to the rank of [rank].";

$l_news_demotedheadline		 ="[name] has been demoted to [rank]";
$l_news_demoted 		 = "The Federation regrets to announce the demotion of [name] to the rank of [rank].";

$l_news_namechangedheadline		 ="[oldname] changed name to [newname]";
$l_news_namechanged 		 = "[oldname] applied to the Federation Review Board to change their name to [newname].  The Federation has granted the name change.  From this day forward [oldname] shall now be known as [newname].  All ships and planets should update their records immediately.";

$l_news_found_planets_short	 = "Federation Survey: [found_planets] new planets located.";
$l_news_found_planets	 = "Federation Survey Scouts have located [found_planets] new planets in recently discovered sectors.";

$l_news_new_ports_short	 = "Federation Survey: [new_ports] new ports constructed.";
$l_news_new_ports	 = "Federation Engineers have constructed [new_ports] new ports in recently discovered sectors.";

$l_news_addedsectors_short	 = "Federation Survey: [addedsectors] sectors discovered.";
$l_news_addedsectors	 = "Federation Survey Scouts have discovered [addedsectors] new sectors.  Caution is advised.";

$l_news_artifactheadline		 ="[playername] completed [artifact]";
$l_news_artifact 		 = "[playername] has found all of the pieces of the [artifact] and has all of the power it can provide.";

$l_news_artifactfoundheadline		 ="[playername] found [artifact] piece";
$l_news_artifactfound 		 = "[playername] has found one of the pieces of the [artifact] and needs [pieces] more [piece].";

?>