<?php
$l_novabomb_title             = "Warp Link Nova Bomb";
$l_novabomb_turns            = "La Bomba Nova richiede almeno 50 turni per fare fuoco.";
$l_novabomb_query             = "Bopmba Nova Settore. Sei sicuro?";
$l_novabomb_yes           = "Si, Fuoco con la Bomba Nova sul settore ";
$l_novabomb_question             = " di fare fuoco con la Bomba Nova sul settore ";
$l_novabomb_success             = " è stato bombardato con la Bomba Nova!";
$l_novabomb_mines            = "Ha distrutto [mines] mine del settore.";
$l_novabomb_fighters            = "Ha distrutto [fighters] droni di pattuglia nel settore.";
$l_novabomb_planetsdamaged            = "Pianeti danneggiati dalal Bomba Nova";
$l_novabomb_planet            = "Pianeta ";
$l_novabomb_damage            = " ha subito danni a causa della Bomba Nova.";
$l_novabomb_shipsdamaged            = "Navi danneggiate dalla Bomba Nova";
$l_novabomb_ship            = "Nave Stellare ";
$l_novabomb_novaexplode   ="La Bomba Nova è esplosa non appena è stata lanciata, e la tua nave ha subito ingenti danni.";
$l_novabomb_novaexplode2   ="La Bomba Nova è esplosa non appena è stata lanciata, e la tua nave è stata distrutta!.";
$l_novabomb_notfedsec   ="La Bomba Nova non può essere usata in settori di proprietà della Federazione.";
?>
