<?php
$l_gns_title             = "Dispositivo Genesis";
$l_gns_turn              = "Ti occorre almeno un turno per utilizzare un dispositivo Genesis.";
$l_gns_onplanet          = "Non puoi usare questo dispositivo mentre sei sulla superficie del pianeta.";
$l_gns_full              = "Questo sistema solare è già pieno.";
$l_gns_planetex          = "C'è già un pianeta in questo settore.";
$l_gns_nogenesis         = "Non hai alcun dispositivo Genesis.";
$l_gns_forbid            = "Non è permesso creare pianeti in questo settore.";
$l_gns_bforbid           = "Le basi di questo settore interferiscono con il tuo dispositivo Genesis. La creazione di pianeti non è possibile.";
$l_gns_pcreate           = "Pianeta creato.";
$l_sgns_title             = "Dispositivo Genesis di Settori";
$l_sgns_pcreate           = "Sector [name] created.";
$l_sgns_nogenesis         = "Non hai alcun dispositivo Genesis di settori.";
$l_sgns_forbid            = "La creazione di un wormhole in questo settore non è permesso.";
$l_sgns_forbid1            = "La creazione di un wormhole nei settori della Federazione non è permesso.";
$l_sgcreate				= "Crea Nuovo Settore Genesis";
$l_sgcreatens				= "Crea Nuova Rotta Genesis verso lo spazio sconosciuto";
$l_sgns_forbid2            = "Più di [limit] rotte in settori SG non sono permesse.";
$l_sgns_forbid3            = "Cannot create Sector Genesis warp link from current sector - that would exceed the maximum of [limit] per sector.";
$l_sgns_nocredits            = "Non hai abbastanza crediti per creare un nuovo settore.";
$l_sgns_shipcredits            = "Crediti sulla nave:";
$l_sgns_createcost            = "Costo per creare un nuovo settore:";
$l_sgns_complete            = "Rotta Spazio Normale Completata";
$l_sgns_sectorname            = "Enter Sector Name:";
$l_gns_max_unbased_planets = "The Federation will not allow the creation of more planets until you have less than [max_unbased_planets] unbased planets.";

?>
