<?php
$l_pre_title             = "Cambia Rotte Spazioreale presettate";
$l_pre_exceed            = "La Rotta SR [preset] eccede il massimo dell'universo di [sector_max]. Non verrà salvata.<BR><BR>";
$l_pre_set               = "Presetta";
$l_pre_save              = "Salva";
$l_pre_info              = "Info";
$l_pre_invalid              = "[sector] is an invalid sector name.";
$l_pre_invalidchange            = "[sector] is a Sector Genesis Sector. Your old preset is unchanged.";
?>
